ndlib/honeycomb

app/controllers/collections_controller.rb
app/views/collections/index.html.erb

* Set the user creating a collection as a curator of that collection.
* Restrict list of collections that a user can see on index page to the collections they can curate. DEC-33

Implementing out some of the unfinished permission stuff

---

app/assets/stylesheets/nav_bar.css.scss
app/assets/stylesheets/ui-customizations.css.scss
app/views/items/index.html.erb
app/views/layouts/application.html.erb
app/views/shared/_top_nav.html.erb

UI - New left nav

---

Gemfile
Gemfile.lock
app/assets/javascripts/components/DragContent.js.jsx
app/assets/javascripts/components/honeypot_image.js.jsx
app/assets/javascripts/components/item.js.jsx
app/assets/javascripts/components/item_list.js.jsx
app/assets/javascripts/components/new_section_dropzone.js.jsx
app/assets/javascripts/components/section.js.jsx
app/assets/javascripts/components/section_description.js.jsx
app/assets/javascripts/components/section_image.js.jsx
app/assets/javascripts/components/section_list.js.jsx
app/assets/javascripts/components/showcase_editor.js.jsx
app/assets/javascripts/components/showcase_editor/SectionDragContent.js.jsx
app/assets/javascripts/components/showcase_editor/ShowcaseEditorTitle.js.jsx
app/assets/javascripts/mixins/DraggableMixin.js.jsx
app/assets/stylesheets/sections.css.scss
app/controllers/sections_controller.rb
app/controllers/showcases_controller.rb
app/models/showcase.rb
app/services/reorder_sections.rb
app/views/sections/index.json.jbuilder
app/views/showcases/edit.html.erb
config/routes.rb
spec/controllers/showcases_controller_spec.rb
spec/services/reorder_sections_spec.rb
spec/spec_helper.rb

Moves all showcase editor styles into the relevant React components.
Refactored styles to make the layout easier to work with.
Created a view component for the showcase title section
Fixed initial order for a new section.
Fixed reorder logic and implemented reorder save.

Refactor showcase editor

---

app/assets/javascripts/components/showcase_editor.js.jsx
app/assets/stylesheets/items.css.scss
app/form/section_form.rb
app/helpers/application_helper.rb
app/views/collections/_list.html.erb
app/views/collections/new.html.erb
app/views/items/_action_bar.html.erb
app/views/items/_edit_action_bar.html.erb
app/views/items/_list.html.erb
app/views/items/edit.html.erb
app/views/sections/_image_form.html.erb
app/views/sections/_text_form.html.erb
app/views/sections/edit.html.erb
app/views/sections/new.html.erb
app/views/shared/_back_action_bar.html.erb
app/views/showcases/_action_bar.html.erb
app/views/showcases/_list.html.erb
app/views/showcases/edit.html.erb
app/views/showcases/index.html.erb
config/locales/en.yml
db/migrate/20150227192806_add_timestamps_to_showcases.rb
db/schema.rb
spec/form/section_form_spec.rb

added back buttons and an action bar

Add action bars

---

app/assets/javascripts/components/itemShowImageBox.js.jsx
app/assets/javascripts/components/openseadragonViewer.js.jsx
app/assets/javascripts/components/thumbnail.js.jsx
app/decorators/item_decorator.rb
spec/decorators/collection_image_spec.rb
spec/decorators/item_decorator_spec.rb

Using local image json to improve image load time.

Local image json

---

app/models/collection.rb
app/models/item.rb
app/models/showcase.rb
app/services/create_beehive_url.rb
app/views/exhibits/edit.html.erb
app/views/items/edit.html.erb
app/views/showcases/_edit_action_bar.html.erb
spec/models/collection_spec.rb
spec/services/create_beehive_url_spec.rb

Not ready yet, just want to see the coveralls report.

Adding CreateBeehiveURL service.

---

app/assets/javascripts/components/showcase_editor/SectionImage.js.jsx
app/assets/javascripts/redactor_field.js.coffee
app/views/exhibits/_form.html.erb
app/views/sections/_image_form.html.erb
app/views/sections/_text_form.html.erb

There is a complimentary change in beehive that will need to be merged simultaneously

Add redactor to caption and site description

---

config/initializers/airbrake.rb
lib/error_helper.rb

Track user's username and name.  Can only use supported attributes from http://git.io/h6YRpA
Also fixes catch_500 to render appropriate template

Notify airbrake in rescue_from

---

config/newrelic.yml

Ha! I can do pull requests too! And, I can use **markdown** in my requests.

Add New Relic

---

app/assets/javascripts/components/showcase_editor/SectionDescription.js.jsx

Similar fix to the one for DEC-187 on beehive.

Showcase editor fix

---

Gemfile
Gemfile.lock
app/models/showcase.rb
app/policy/user_is_editor.rb
app/services/save_honeypot_image.rb
config/application.rb
config/environments/pre_production.rb
config/environments/production.rb
config/environments/test.rb
spec/decorators/nav/top_spec.rb
spec/form/section_form_spec.rb
spec/models/site_permission_spec.rb
spec/models/user_spec.rb
spec/policy/section_type_spec.rb
spec/policy/user_is_editor_spec.rb
spec/services/find_or_create_user_spec.rb
spec/services/map_user_to_api_spec.rb
spec/services/masquerade_spec.rb

Upgraded Rails, removed rspec deprecations

Upgrade to Rails 4.2

---

.gitignore
app/controllers/collections_controller.rb
app/policy/collection_is_published.rb
app/queries/collection_query.rb
app/services/publish.rb
config/routes.rb
db/migrate/20150416184347_add_published_to_collections.rb
db/schema.rb
spec/controllers/collections_controller_spec.rb
spec/policy/collection_is_published_spec.rb
spec/queries/collection_query_spec.rb

I've not added in any UI elements to manage the published status for collections

Add publish status collections

---

app/views/sections/_image_form.html.erb

**What** Bug fix for DEC-237 - relational integrity issue when item deleted that is attached to a showcase
**Why** It's a bug!
**How** Created a conditional in the relevant view that tests for the existence of the item in question

Apply fix for deleted item record

---

app/controllers/collections_controller.rb
app/decorators/v1/collection_json_decorator.rb
app/views/collections/_form.html.erb
app/views/v1/collections/_collection.json.jbuilder
config/locales/en.yml
db/migrate/20150501195915_add_collections_subtitle.rb
db/schema.rb
spec/decorators/v1/collection_json_decorator_spec.rb
spec/models/collection_spec.rb

We need a subtitle style field for collection names to display names across 2 lines. 
I updated the database, updated the form and added the field to the api.

Add collection subtitle

---

app/decorators/v1/showcase_json_decorator.rb
app/queries/showcase_query.rb
app/views/v1/showcases/show.json.jbuilder

Adding next/previous showcase to the API. https://github.com/ndlib/beehive/pull/93 depends on this pull.

DEC-268: Next/previous showcase

---

app/assets/javascripts/components/forms/FormRow.js.jsx
app/assets/javascripts/components/forms/ItemMetaDataForm.js.jsx
app/assets/javascripts/components/forms/StringField.js.jsx
app/assets/javascripts/components/forms/TextField.js.jsx

I did not take into account that the errors were arrays.  
Changes to process errors as an array.

update the errors to process the arrays

---

app/assets/javascripts/components/showcase_editor/ShowcaseEditorTitle.js.jsx
app/controllers/showcases_controller.rb
app/decorators/showcase_decorator.rb
app/views/showcases/show.json.jbuilder

Why 
The subtitle value is not saving on the showcases
How 
Added it to the params listed in the controller.  Then made is show up on the display in the editor.  
this will be in conflict with changes going into phase2.

Fix showcase saveing params

---

app/assets/javascripts/components/forms/ItemMetaDataForm.js.jsx
app/assets/javascripts/components/showcase_editor/ShowcaseEditorTitle.js.jsx
app/controllers/exhibits_controller.rb
app/controllers/showcases_controller.rb
app/controllers/v1/items_controller.rb
app/decorators/item_decorator.rb
app/decorators/showcase_decorator.rb
app/decorators/v1/collection_json_decorator.rb
app/services/create_beehive_url.rb
app/services/ensure_collection_has_exhibit.rb
app/values/cache_keys/custom/v1_showcases.rb
app/values/cache_keys/generator.rb
app/views/exhibits/_copyright_text_form.html.erb
app/views/layouts/application.html.erb
app/views/layouts/modal.html.erb
app/views/showcases/show.json.jbuilder
app/views/v1/collections/_collection.json.jbuilder
db/migrate/20150527193045_add_copyright_to_exhibits.rb
db/schema.rb
spec/controllers/v1/showcases_controller_spec.rb
spec/decorators/item_decorator_spec.rb
spec/decorators/v1/collection_json_decorator_spec.rb
spec/models/exhibit_spec.rb
spec/services/create_beehive_url_spec.rb
spec/services/ensure_collection_has_exhibit_spec.rb
spec/values/cache_keys/custom/v1_showcases_spec.rb

Need to catch phase2 up to the changes made on master

Master to phase2 merge

---

app/decorators/v1/collection_json_decorator.rb
app/models/collection.rb
app/services/create_beehive_url.rb
app/views/exhibits/edit.html.erb
spec/decorators/v1/collection_json_decorator_spec.rb
spec/models/collection_spec.rb

**WHAT**
* Remove slug and beehive_url methods to avoid redundancy
* Remove call to slug method
* Remove call to slug method
* Remove call to slug method
* Remove call to beehive_url method
**WHY** This is the same sort of cleanup I did on the item model

Cleanup of collection model

---

Gemfile
Gemfile.lock

**WHAT** Update version of mime types gem
**WHY** Saves up to 20% on RAM usage

Update mime types to save on RAM

---

app/assets/javascripts/components.js
app/assets/javascripts/components/ReactDropzone.jsx
app/assets/javascripts/mixins/MuiThemeMixin.jsx
app/assets/javascripts/themes/HoneycombTheme.jsx
app/views/items/_action_bar.html.erb
app/views/items/index.html.erb
app/views/layouts/application.html.erb

First pass, and proof of concept on implementing Material UI throughout site using Material UI for ReactDropzone widget add the button that triggers it.
DEC-467: Created theme based off of light theme and our customizations for material design to use with Material-UI.

DEC-398: Implement Material UI throughout site

---

app/views/items/edit.html.erb

Description:
I think we should just hide this whole section but that should be raised before it is done.
https://jira.library.nd.edu/browse/DEC-505

Hiding broken sub resources on item edit page.

---

app/assets/javascripts/components/forms/ItemMetaDataForm.jsx

@jonhartzler What do you think of this to simplify the long if..else statement?  It seemed like there was a lot of code repetition going on.

Simplify field component rendering

---

app/views/exhibits/edit.html.erb
app/views/items/edit.html.erb
app/views/shared/_collection_left_nav.html.erb

What: Fixed preview button for items; reworded the left nav options; removed the site preview button on the site setup page;
How: Some very simple ERB edits

Dec 522 523 524 preview mode fixes

---

app/assets/javascripts/components.js
app/assets/javascripts/components/PageMessage.jsx
app/decorators/display_flash_message.rb
app/views/layouts/application.html.erb
spec/decorators/display_flash_message_spec.rb

I changed the messaging so it always uses the snackbar,  This adds

Add snackbar for page messages

---

Capfile
Gemfile
Gemfile.lock
app/services/map_user_to_api.rb
app/services/notify_error.rb
app/workers/retry_worker.rb
config/deploy.rb
config/schedule.rb
lib/tasks/sneakers.rake
spec/services/map_user_to_api_spec.rb
spec/services/notify_error_spec.rb
spec/workers/retry_worker_spec.rb

I was going to write some code that would make use of the NotifyError service, but wanted to get the updated version from the Annex.
I also pulled in the updates to the Sneakers rake task that is being used on Annex, and added the cron task to make sure Sneakers is running.
In MapUserToAPI updated the NotifyError call, and broke down the map! method to satisfy the linter.

Updates from annex

---

app/assets/javascripts/components/forms/ItemMetaDataForm.jsx
app/assets/javascripts/mixins/MuiThemeMixin.jsx

What: Changed the metadata form menu from a standard select box to a material-ui component; Updated the styles; Refactored the ItemMetaDataForm react component.

DEC-417 Restyle drop down as material-ui component

---

app/assets/javascripts/components/forms/ItemMetaDataForm.jsx

updated the message that appears in the snack bar on form error.

Dec 546 update form error warning

---

app/values/metadata_date.rb
app/values/metadata_date/convert_to_iso_date.rb
app/values/metadata_date/convert_to_ruby_date.rb
spec/values/metadata_date/convert_to_iso_date_spec.rb
spec/values/metadata_date/convert_to_ruby_date_spec.rb

It was requiring month and day.  To fix this I allowed blank in the validations and I then needed to remove  blank rows from the ruby convert to date class.

fix the validations on the date field

---

app/models/honeypot_image.rb
app/queries/exhibit_query.rb
app/values/cache_keys/custom/v1_collections.rb
app/values/cache_keys/custom/v1_showcases.rb
spec/controllers/v1/collections_controller_spec.rb
spec/controllers/v1/showcases_controller_spec.rb
spec/queries/exhibit_query_spec.rb
spec/values/cache_keys/custom/v1_collections_spec.rb
spec/values/cache_keys/custom/v1_showcases_spec.rb

Fixes for most of the caching problems found during our recent round of testing.

Caching problems

---

app/assets/javascripts/components/ItemImageZoomButton.jsx
app/assets/javascripts/openseadragon.js

Why: the old modal was being used for the zoom link.  Also it was not working.  Now it works and we are using material-ui.  I also updated open seadragon

Update the modal to work with new openseadragon

---

app/views/sections/_show.json.jbuilder

Fixing a bug if the section is text only (no associated item)

Section image bug fix

---

.travis.yml
app/assets/javascripts/components/forms/ItemMetaDataForm.jsx

What: Suppressed the metadata field drop down when all metadata fields have been selected or filled in for an item.
How: Modified the ItemMetaDataForm component so that the additionalFields method tracks the number of displayed fields against the total additional field count and suppresses the drop down if they match.

DEC-418 Drop down suppressed appropriately

---

Gemfile
Gemfile.lock

https://github.com/ndlib/beehive/pull/181

Fix components unmounting on window unload.

---

app/assets/javascripts/components/ItemShowImageBox.jsx

Why: Fix for https://docs.google.com/document/d/19a97aJPiSRvBgxIGKkIkcpViOg5_Iou3OvUgcgHItXM/edit#bookmark=id.g8xtpr1ochgj
How: Problem was that it was firing off an ajax request and testing the request count at the same time. Moved the count test to only happen when we get a processing response from the server. Added an additional guard to prevent firing another request when the previous is still awaiting a response. This could theoretically cause the wait to be longer than 15 seconds if the server takes longer than 5s to respond on any one request.

Image displays with error

---

app/controllers/v1/collections_controller.rb
app/decorators/v1/metadata_configuration_json.rb
app/models/metadata/configuration.rb
app/models/metadata/configuration/field.rb
config/metadata/item.yml
config/routes.rb
spec/decorators/v1/metadata_configuration_json_spec.rb
spec/models/metadata/configuration/field_spec.rb
spec/models/metadata/configuration_spec.rb

First pull request for just the api endpoint of the metadata configuration.

Dec 566 add api end point for metadata configuration.

---

app/assets/stylesheets/ui-customizations.css.scss
app/views/import/_import_results.html.erb
app/views/import/import_google_sheet_callback.html.erb
app/views/layouts/application.html.erb

Adding back/feedback buttons to the import results.

DEC-589: Add back button to import results

---

.gitignore
app/models/waggle/adapters/solr/search/hit.rb
app/models/waggle/search/hit.rb
spec/models/waggle/adapters/solr/search/hit_spec.rb
spec/models/waggle/search/hit_spec.rb

Previously both fields were left nil.

Add description and short description to search api

---

.rubocop.yml
app/assets/javascripts/components/showcase_editor/Section.jsx
app/controllers/sections_controller.rb
app/decorators/v1/section_json_decorator.rb
app/views/sections/_image_form.html.erb
app/views/sections/_show.json.jbuilder
app/views/sections/_text_form.html.erb
app/views/v1/sections/_section.json.jbuilder
db/migrate/20151005195020_add_has_spacer_to_section.rb
db/schema.rb

updates to allow spacing in the showcase

---

app/decorators/v1/collection_json_decorator.rb
app/models/exhibition.rb
db/migrate/20151008201702_migrate_url_from_exhibits_to_collections.rb
db/schema.rb
spec/decorators/v1/collection_json_decorator_spec.rb

What: Schema, code and data migration of URL field from the exhibit model to the collection model
How: Code, schema and data migrated

DEC-616 Migration of url field to collection model

---

app/assets/javascripts/components/HoneypotImage.jsx
app/assets/javascripts/components/showcase_editor/Item.jsx
app/controllers/api/items_controller.rb
config/settings.yml

What: Change beehive alias setting to point to collections.library.nd.edu

Beehive alias fix

---

app/assets/javascripts/actions/MetaDataConfigurationActions.js
app/assets/javascripts/components/forms/MetaDataFieldDialog.jsx
app/assets/javascripts/components/forms/MetadataConfigurationForm.jsx
app/assets/javascripts/stores/MetaDataConfigurationStore.js
app/controllers/v1/collections_controller.rb
app/controllers/v1/configurations_controller.rb
app/controllers/v1/metadata_fields_controller.rb
app/decorators/v1/collection_json_decorator.rb
app/models/metadata/configuration.rb
app/models/metadata/configuration/field.rb
app/services/metadata/update_configuration_field.rb
app/views/collections/_metadata_settings_form.html.erb
config/routes.rb
spec/controllers/v1/collections_controller_spec.rb
spec/controllers/v1/configurations_controller_spec.rb
spec/controllers/v1/metadata_fields_controller_spec.rb
spec/decorators/v1/collection_json_decorator_spec.rb
spec/models/metadata/configuration/field_spec.rb
spec/models/metadata/configuration_spec.rb
spec/services/metatdata/update_configuration_field_spec.rb

Here I updated the configuration to have an update service.  This is the first part of DEC-766.  The second part is coming soon!!

Dec 766 allow metaconfig to be updated

---

app/assets/stylesheets/ui-customizations.css.scss
app/views/pages/_form.html.erb

Made changes to the page redactor editor styles to match the pages in beehive

DEC-787: User would like page editor to be wysiwyg

---

app/decorators/item_json.rb
app/decorators/v1/item_json_decorator.rb
spec/decorators/item_json_spec.rb
spec/decorators/v1/item_json_decorator_spec.rb

We need to have the user defined id in the api.  
It is now there.

add user defined id to the api.

---

app/services/brood/collection.rb
app/services/brood/record.rb
app/services/brood/set.rb
app/services/create_collection_configuration.rb
spec/models/metadata/configuration/config_yml_spec.rb
spec/services/create_collection_configuration_spec.rb

so that we can have vatican data in the seeds.

Update seed task

---

config/metadata/vatican_item.yml

What: Initial yaml file for the Vatican project metadata
Why: Because we need it!!!

DEC-817 Initial yaml file for Vatican project

---

app/views/items/_list.html.erb
app/views/sections/_show.json.jbuilder

Changed references to the local paperclip thumbnails to now use the image server in the items list and showcase editor.

DEC-839: Images are broken in a few places

---

config/settings.yml

S3 does not respond to https, changed urls to http.

DEC-848: Preview links are dead

---

app/assets/javascripts/components/forms/SiteObjectCard.jsx

JS interpreter was having trouble with the const function reference connectDragSource.

DEC-849: Cannot edit sitepath

---

app/services/brood/set.rb
config/metadata/vatican_item.yml
spec/models/metadata/configuration/config_yml_spec.rb

What: Update the vatican metadata config so that it matches the latest data set

DEC-889 Update vatican yaml config

---

app/assets/javascripts/actions/MetaDataConfigurationActions.js
app/assets/javascripts/components/forms/MetaDataConfigurationForm.jsx
app/assets/javascripts/components/forms/MetaDataFieldDialog.jsx
app/assets/javascripts/components/forms/SiteObjectCard.jsx
app/assets/javascripts/components/forms/SiteObjectEventTypes.jsx
app/assets/javascripts/components/forms/StylableDropTarget.jsx
app/assets/javascripts/mixins/GoogleCreatorMixin.jsx

Why: A show stopping bug is preventing JS functionality from executing on Safari. The browser is reporting a 'const' error, which is preventing React and jQuery from initializing.
How: Replaced all const with var.

DEC-924: Bugfix Safari const

---

lib/tasks/adhoc_upload_images.rake

Why: It will be easier to import Ambrosiana if we can import the images from the current website.
How: Modified the image upload task to allow for http based files. Now also prints which files were successfully imported. This way, if we have to bail in the middle for any reason, we can exclude these from the full list when running again.

DEC-930: Ambrosiana import

---

app/assets/javascripts/application.js
app/assets/javascripts/components.js

Moving the polyfill to components.js. Is causing problems with the asset precompile on preprod/prod.

DEC-925: Promise polyfill deploy bug

---

app/models/collection.rb
app/services/set_collection_slug.rb
db/migrate/20160606174800_add_custom_slug_to_collections.rb
db/schema.rb
spec/models/collection_spec.rb
spec/services/set_collection_slug_spec.rb

What: Added a field to the collection model that can store a custom URL slug that the user creates
How: Added field to model, added service class that can set the slug value or raise the appropriate exception

DEC-1048 Added custom slug field for collections

---

app/assets/javascripts/components/utils/dismissDialog.jsx

What: Unfortunately, we have to say "adios" to "Adios", as much as I hate to.
How: Super secret complicated process that involves aliens, FBI agents, the NSA and former KGB members.

DEC-1065 Adios adios

---

app/assets/stylesheets/ui-customizations.css.scss
app/views/layouts/application.html.erb

added the env notice to pprd 

---

app/services/create_url_slug.rb
spec/services/create_url_slug_spec.rb

Same fix that was just merged into master

DEC-1090 Fix for custom slug bug

---

app/controllers/v1/configurations_controller.rb
app/decorators/v1/collection_json_decorator.rb
app/decorators/v1/metadata_configuration_json.rb
app/views/v1/collections/_collection.json.jbuilder
spec/decorators/v1/collection_json_decorator_spec.rb
spec/decorators/v1/metadata_configuration_json_spec.rb

updates to the configuration so that it can put configuration options of enable search and browse in the configuration.

Configuration api updates

---

Gemfile.lock
config/deploy.rb

Includes a bug fix for compatibility with Rake 11: https://github.com/capistrano/capistrano/pull/1631

Updating capistrano to 3.5

---

app/assets/javascripts/components/showcase_editor/SectionDragContent.jsx
app/assets/javascripts/components/showcase_editor/ShowcaseEditor.jsx
app/assets/javascripts/mixins/HorizontalScrollMixin.jsx

As a side note.  There are several warnings I did not correct.  If some one believes I should go back I can try to address those.

DEC-1098 fix the drag and the scrolling.

---

app/controllers/v1/collections_controller.rb
app/queries/collection_query.rb
spec/controllers/v1/collections_controller_spec.rb
spec/queries/collection_query_spec.rb

unpublished collections were unavailable on the home page.

---

app/assets/javascripts/components/forms/HtmlField.jsx

redactor updated the interface for how events are added.  this was not working in the react class.

fix issue with redactor not saving

---

.codeclimate.yml
.travis.yml
Gemfile
Gemfile.lock
app/views/collections/settings.html.erb
app/views/collections/site_setup.html.erb
spec/spec_helper.rb

Fixed this so code climate does not show a critical warning.  I know this is smoke and mirrors...

code climate

---

app/assets/javascripts/components/forms/ItemMetaDataForm.jsx
app/views/items/edit.html.erb
config/locales/en.yml

Add title to page. Remove panels from javascript form.
Also modified title for edit page to only say edit.

Standardize format of item edit page

---

app/queries/item_query.rb
spec/queries/item_query_spec.rb

Fix a missed spot for the transition from images to media.

fix bug with image and media

---

app/controllers/v1/media_controller.rb
app/services/serialize_media.rb
config/routes.rb
spec/controllers/v1/media_controller_spec.rb

**Goal**: Provide a controller action that can be used to upload a media thumbnail image
**Work**: Added the method plus specs, and route

DEC-1176 Add controller action for uploading media thumbnails

---

app/services/replace_page_item.rb
spec/services/replace_page_item_spec.rb

Some minor code cleanup as well.

Fixed import bug, added a simple test for this code

---

Gemfile.lock
app/assets/javascripts/components/forms/ItemForm/AddNewItemsButton.jsx
app/assets/javascripts/components/forms/ItemForm/NoMediaForm.jsx
app/assets/javascripts/components/forms/ItemForm/ReplaceMediaForm.jsx
app/assets/javascripts/components/forms/ItemForm/StreamingForm.jsx
app/models/waggle/item.rb
config/environments/pre_production.rb
config/settings.yml
spec/models/waggle/item_spec.rb

The basic problem was that multiple components attached to the add item button components were listening for the ItemCreated Event.  This caused undesirable events to fire.  
To test.  look at the add item button and update the video it should finish uploading before it tries to go to the next step.

DEC-1190 Bug with add button

---

app/controllers/collections_controller.rb

Order collections index so newest are first

re-order the collection index page

---

app/assets/javascripts/components/showcase_editor/Item.jsx
app/assets/javascripts/components/showcase_editor/ItemList.jsx

In all the shuffling of how the showcase editor works the overlay for media thumbnails got broken.

Showcase Media Overlay Fix

---

app/decorators/v1/item_json_decorator.rb
app/models/waggle/item.rb
app/views/v1/search/_hit.json.jbuilder
spec/decorators/v1/item_json_decorator_spec.rb
spec/fixtures/v1/items/pig-in-mud.json

Changed all of the item outputs to use isPartOf/item to be more consistent. Was causing problems with handling data on zucchetto

Consistent isPartOf/item 

---

app/models/waggle/adapters/solr/search/hit.rb
app/models/waggle/search/hit.rb
spec/models/waggle/search/hit_spec.rb

Changed short_description to be pulled from the item instead of making up a value

Meta short description

---

spec/newman/README.md
spec/newman/honeycomb.postman_collection.json

feat(qa): add specs to test connectivity to API

---

app/values/cache_keys/custom/sections.rb
spec/factories/user.rb
spec/models/collection_spec.rb
spec/models/user_spec.rb
spec/models/waggle/adapters/solr/search/result_spec.rb
spec/rails_helper.rb
spec/services/destroy/collection_spec.rb
spec/services/destroy/collection_user_spec.rb
spec/services/destroy/user_spec.rb
spec/support/controller_helpers.rb

Mainly it was just that the specs were failing to authenticate after Okta changes. CI build should succeed now.

Fix unit tests.

---

app/assets/javascripts/actions/MetaDataConfigurationActions.js
app/assets/javascripts/components/forms/MetaDataConfigurationForm/MetaDataConfigurationFacetItem.jsx
app/assets/javascripts/components/forms/MetaDataConfigurationForm/MetaDataConfigurationFacets.jsx
app/assets/javascripts/components/forms/MetaDataFacetDialog.jsx
app/assets/javascripts/stores/MetaDataConfigurationStore.js

I tested it this time and now it actually does build and deploy to prep fine.

Convert JS to valid ES5 syntax

---

app/decorators/v1/collection_json_decorator.rb
app/views/v1/collections/_collection.json.jbuilder
db/dec_scraper.py
spec/fixtures/v1/items/pig-in-mud.json

Don't really know what would use this, but there was a lingering bug ticket and it was easy to add so there ya go.

DEC-1213 Add hasPart/pages to API response

---

config/environments/development.rb
config/secrets.example.yml
db/seeds.rb
docker-compose.yml
docker/Dockerfile.rails
docker/Dockerfile.solr
docker/README.md
docker/database.yml
docker/rails_entry.sh
docker/solr.yml
docker/wait-for-it.sh

This adds all the files and changes to create a rudimentary development environment within Docker.
Docker will create three containers: one for Postgres, one for Solr, and one for Ruby.
Instructions are also included in the `docker/` folder.

Create dockerized environment

---

docker-compose.prod.yml
docker/Dockerfile.nginx
docker/nginx.conf
docker/nginx_entry.sh

adding in nginx container to be able to run separate services, similar to our other services

nginx docker
