ndlib/honeycomb

app/views/items/_form.html.erb, app/views/items/_list.html.erb
**What** I added the redactor editor to the item description and transcript fields in the UI
**How** I modified a couple of view partials, one for the item edit page, and one associated with the item list for a collection
**Why** The form output for the item edit page needed to be changed to remove the old type, and add a class that renders the redactor editing tools; the description needed to be changed on the item list so that it output raw HTML instead of using the standard Draper helper method to accomodate HTML in the descriptive field
**Note** Beehive will need to be updated to accommodate for HTML being in the item description and transcript fields (see image):
=> Add redector to item description and transcript fields

app/controllers/v1/items_controller.rb, app/controllers/v1/sections_controller.rb, app/controllers/v1/showcases_controller.rb, spec/controllers/v1/items_controller_spec.rb, spec/controllers/v1/sections_controller_spec.rb, spec/controllers/v1/showcases_controller_spec.rb
These changes should capture all needed data for all v1 controllers when generating etags.
=> DEC-243: V1/Controller caching

app/controllers/exhibits_controller.rb, app/decorators/v1/collection_json_decorator.rb, app/views/exhibits/_form.html.erb, app/views/exhibits/edit.html.erb, app/views/v1/collections/_collection.json.jbuilder, config/locales/en.yml, db/migrate/20150430164752_add_short_intro_to_collection.rb, db/schema.rb, spec/decorators/v1/collection_json_decorator_spec.rb
Beehive needs to have a separation between the site introduction and the introduction for the exhibit.  
To do this I added a field to the exhibit table, added the field to the exhibit form, and added the field to the api.
=> Add site introduction 

app/decorators/v1/showcase_json_decorator.rb, app/views/showcases/_form.html.erb, app/views/v1/showcases/_showcase.json.jbuilder, config/locales/en.yml, db/migrate/20150504153937_add_subtitle_to_showcases.rb, db/schema.rb, spec/decorators/v1/showcase_json_decorator_spec.rb
I updated showcases to do the same thing with titling i did with collections so we have control over 2 line titles. 
In the api there is a title, title_line_1 and title_line_2, and a description.  Title is title_line_1 + title_line 2.   In addition the showcase table stores the data as title, subtitle and description.
=> Update showcase titling

app/views/v1/showcases/_showcase.json.jbuilder
Fix a typo in _showcase.json.builder that overwrote title with title_line_2.
=> Quick fix for Showcase JSON Titles

app/controllers/exhibits_controller.rb, db/migrate/20150505125702_add_created_updated_dates_to_exhibits.rb, db/schema.rb, spec/controllers/exhibits_controller_spec.rb, spec/models/exhibit_spec.rb
This will add updated_at and created_at date fields so that caching will work properly. Please note that it does perform a data update within the migration.
=> Exhibits updated/created dates

Gemfile, Gemfile.lock, app/controllers/admin/administrators_controller.rb, app/controllers/v1/collections_controller.rb, app/controllers/v1/items_controller.rb, app/controllers/v1/sections_controller.rb, app/controllers/v1/showcases_controller.rb, app/decorators/v1/section_json_decorator.rb, app/values/cache_keys/active_record.rb, app/values/cache_keys/custom/administrators.rb, app/values/cache_keys/custom/v1_collections.rb, app/values/cache_keys/custom/v1_items.rb, app/values/cache_keys/custom/v1_sections.rb, app/values/cache_keys/custom/v1_showcases.rb, app/values/cache_keys/decorated_active_record.rb, app/values/cache_keys/generator.rb, config/application.rb, spec/controllers/admin/administrators_controller_spec.rb, spec/controllers/v1/collections_controller_spec.rb, spec/controllers/v1/items_controller_spec.rb, spec/controllers/v1/sections_controller_spec.rb, spec/controllers/v1/showcases_controller_spec.rb, spec/values/cache_keys/active_record_spec.rb, spec/values/cache_keys/custom/administrators_spec.rb, spec/values/cache_keys/custom/v1_collections_spec.rb, spec/values/cache_keys/custom/v1_items_spec.rb, spec/values/cache_keys/custom/v1_sections_spec.rb, spec/values/cache_keys/custom/v1_showcases_spec.rb, spec/values/cache_keys/decorated_active_record_spec.rb, spec/values/cache_keys/generator_spec.rb
Cache keys used for etag generation are now being handled by CacheKeys::Generator classes. For now I only have the v1 controllers implemented so that we can review how this is being handled. If we like this, then I can do the rest of the controllers.
=> Cache key generators for v1

Gemfile, Gemfile.lock, app/controllers/exhibits_controller.rb, app/decorators/v1/collection_json_decorator.rb, app/presenters/exhibits/side_nav_presenter.rb, app/views/exhibits/_about_text_form.html.erb, app/views/exhibits/_copyright_text_form.html.erb, app/views/exhibits/_exhibit_introduction_form.html.erb, app/views/exhibits/_form.html.erb, app/views/exhibits/_side_nav.html.curly, app/views/exhibits/edit.html.erb, app/views/v1/collections/_collection.json.jbuilder, config/application.rb, config/routes.rb, spec/decorators/v1/collection_json_decorator_spec.rb, spec/models/exhibit_spec.rb, spec/presenters/exhibits/side_nav_presenter_spec.rb
We needed a way for the admin to edit the button on the info text. 
To do this I added the a field to the exhibit class, edited the site editor section of the site to have a text area, and I added the about text to the api.  In addition I refactored the way the site editor works so that we can have the different texts on different pages.   
Also I added curly into the project as an example.  You can see how curly was used in side_nav_presenter.rb, _side_nav.html.erb, and side_nav_presenter_spec.rb.   I believe we can easily remove this test if we decide we really don't like it.
=> Add about text

app/controllers/admin/administrators_controller.rb, app/controllers/collections_controller.rb, app/controllers/editors_controller.rb, app/controllers/exhibits_controller.rb, app/controllers/items_controller.rb, app/controllers/sections_controller.rb, app/controllers/showcases_controller.rb, app/values/cache_keys/custom/administrators.rb, app/values/cache_keys/custom/collections.rb, app/values/cache_keys/custom/editors.rb, app/values/cache_keys/custom/exhibits.rb, app/values/cache_keys/custom/items.rb, app/values/cache_keys/custom/sections.rb, app/values/cache_keys/custom/showcases.rb, spec/controllers/admin/administrators_controller_spec.rb, spec/controllers/collections_controller_spec.rb, spec/controllers/editors_controller_spec.rb, spec/controllers/exhibits_controller_spec.rb, spec/controllers/items_controller_spec.rb, spec/controllers/sections_controller_spec.rb, spec/controllers/showcases_controller_spec.rb, spec/values/cache_keys/custom/administrators_spec.rb, spec/values/cache_keys/custom/collections_spec.rb, spec/values/cache_keys/custom/editors_spec.rb, spec/values/cache_keys/custom/exhibits_spec.rb, spec/values/cache_keys/custom/items_spec.rb, spec/values/cache_keys/custom/sections_spec.rb, spec/values/cache_keys/custom/showcases_spec.rb
V1 controllers were handled with a previous merge. This one finishes converting remaining controllers to use the new cache key generator pattern.
=> DEC-279: Rewrite remaining controllers to use cache key generators

app/decorators/v1/item_json_decorator.rb, app/views/v1/collections/_collection.json.jbuilder, app/views/v1/items/_item.json.jbuilder, app/views/v1/sections/_section.json.jbuilder, app/views/v1/showcases/_showcase.json.jbuilder, spec/decorators/v1/item_json_decorator_spec.rb
Changes all API objects to use 'Name' instead of 'Title' for all fields. This is simply a remapping of name to title, ie it does not change the schema or models, just the front-end facing jsons and metadata.
This must be merged with https://github.com/ndlib/beehive/pull/92
=> DEC-265: Title -> Name

app/values/cache_keys/generator.rb, config/initializers/caching.rb, spec/values/cache_keys/generator_spec.rb
On start, the application will now generate a unique key that will be prepended to all cache key strings used to generate etags, causing all etags to change after a restart of the server.
=> DEC-308-Bust the cache on redeploy

app/values/cache_keys/custom/v1_showcases.rb, app/values/cache_keys/generator.rb, spec/controllers/v1/showcases_controller_spec.rb, spec/values/cache_keys/custom/v1_showcases_spec.rb
WHY: Problem was with v1::showcases#index. View used exhibit data but cache key generation was not including this. 
HOW: Changed the v1::showcases#index to use the associated exhibit when generating the cache key.
=> DEC-359: Updating an exhibit does not show changes on refresh

app/controllers/exhibits_controller.rb, app/decorators/v1/collection_json_decorator.rb, app/services/ensure_collection_has_exhibit.rb, app/views/exhibits/_copyright_text_form.html.erb, app/views/v1/collections/_collection.json.jbuilder, db/migrate/20150527193045_add_copyright_to_exhibits.rb, db/schema.rb, spec/decorators/v1/collection_json_decorator_spec.rb, spec/models/exhibit_spec.rb, spec/services/ensure_collection_has_exhibit_spec.rb
WHY: The user may need to include additional copyright details for their exhibit
HOW: Added a copyright field to the exhibits schema and modified honeycomb to allow editing of this field. If the user specifies a custom copyright, it will use it, otherwise, it will use the previously defined copyright text. As an additional note, when the user first creates an exhibit, it will create a default value so that the copyright year is associated with the year in which the exhibit was originally created, as opposed to a dynamically changing value. They can of course always modify this after it's created.
=> DEC-262: Allow the copyright text to be changed

app/services/create_beehive_url.rb, spec/services/create_beehive_url_spec.rb
WHY: The preview button for an item linked to a dead route
HOW: Changed the way CreateBeehiveURL handles creating the url for items.
=> DEC-354: Item preview link is broken in honeycomb 

config/locales/en.yml
Deleting a showcase gives this flash message: "translation missing: en.showcases.destroy.success". Added a showcase destroy success and failure message.
=> DEC-352: Delete showcase translation error

app/controllers/v1/items_controller.rb, app/models/item.rb, app/values/cache_keys/custom/v1_items.rb, app/views/v1/items/showcases.json.jbuilder, config/routes.rb, spec/controllers/v1/items_controller_spec.rb, spec/models/item_spec.rb, spec/values/cache_keys/custom/v1_items_spec.rb
Need a way of getting a json from the api for all showcases that use an item. To do this, I added a new route v1/items/:id/showcases which hits ItemsController.showcases. This action will render a json with the following structure:
Collection
--Item
----Showcases
where Showcases will only contain showcases that use that item.
=> DEC-389: Get showcases dependent on item

app/controllers/v1/showcases_controller.rb, app/decorators/v1/showcase_json_decorator.rb, app/values/cache_keys/custom/v1_showcases.rb, spec/controllers/v1/showcases_controller_spec.rb, spec/values/cache_keys/custom/v1_showcases_spec.rb
WHY: Changing the order of showcases does not show changes on front end. 
HOW:
-Had to start passing the decorated showcase to the cache key generator so that it could pull in the next showcase when generating the cache key.
-Changed the specs now that the cache key generator uses a ShowcaseJSONDecorator object and not just a Showcase object.
=> DEC-388: Showcase order caching

app/assets/javascripts/components/embed/EmbedCode.js.jsx, app/assets/javascripts/components/forms/ItemMetaDataForm.js.jsx, app/decorators/item_decorator.rb, app/decorators/v1/item_json_decorator.rb, app/views/v1/items/_item.json.jbuilder, spec/decorators/item_decorator_spec.rb, spec/decorators/v1/item_json_decorator_spec.rb
Update to have a select box to add 5 new meta data fields to item.  
The things I want to say about this branch are more informational since I am leaving.  I think I would like to get it merged in while I am gone so that master does not drift so much.  There are several unpolished parts that I have added tickets for.  
1.  It is a select box and it should probably be a drop button.
2.  The select box does not disappear when there are no items in it. 
3.  new fields appear in the order they are listed in the additionalFieldConfiguration hash and not at the bottom of the form.  
4.  I also think the mechanism for doing this needs some refactoring but I am expecting that to happen with the other tickets revolving around the metadata display.
=> Dec 315 add react fields

app/controllers/items_controller.rb, spec/controllers/items_controller_spec.rb
Why: Item update is now handled in the v1 controller
How: Removed the action from the previous ItemsController and updated the specs to match.
=> DEC-337: Remove update from ItemsController 

app/assets/javascripts/components/ShowcasesPanel.js.jsx, app/assets/javascripts/mixins/TitleConcatMixin.js.jsx, app/assets/stylesheets/ui-customizations.css.scss, app/decorators/item_decorator.rb, app/decorators/showcase_json_decorator.rb, app/views/items/edit.html.erb, app/views/showcases/_showcases.json.jbuilder, spec/decorators/item_decorator_spec.rb, spec/decorators/showcase_json_decorator_spec.rb
Why: Need to add the list of showcases that are using the item to the item edit view
How:
- Created a ShowcasesPanel to handle rendering the showcase list. This is not tied to items in anyway, so it can be reused to show other brief showcase lists
- Added a title concat mixin (from beehive) to handle generation of the full name of the showcase
- Since we are unable to use the api for this yet, I had to recreate the json generation that was happening inside of the v1 controllers, except this one uses id instead of unique id and links to the non v1 controllers. So ItemDecorator now has a showcases_json method that renders a json with all the needed data for the item's related showcases
=> DEC-392: Add showcases to the item edit view

app/decorators/v1/item_json_decorator.rb, app/models/item.rb, app/services/create_beehive_url.rb, app/views/items/edit.html.erb, app/views/v1/items/_item.json.jbuilder, db/schema.rb, spec/decorators/v1/item_json_decorator_spec.rb, spec/models/item_spec.rb
**WHAT** Some methods were removed from the Item model because they had inherent redundancies
**WHY** To simplify the Item model
**HOW** I removed the two methods in question, and changed some of the view and decorator code so that the service classes are called directly instead of having callbacks embedded in the Item model
=> Dec 371 item model cleanup

app/decorators/delete_panel.rb, app/queries/item_query.rb, app/views/items/edit.html.erb, app/views/shared/_delete_panel.html.erb, config/locales/en.yml, spec/decorators/delete_panel_spec.rb
**Why**: We are adding a list of related showcases to the item edit view, but we also want to additionally give a stronger warning to the user near the delete button if the item is in use by a showcase.
**How**: There are several pages that use the DeletePanel object to render this panel. I extended this class to allow injection of a query object that implements a can_delete method. I wanted to make this as abstract as possible to let those queries answer a high level question of whether or not an object can or cannot be deleted. I also changed it to disable the delete button for now until we implement a cascading delete for items. Once we implement that it will be easy enough to change the warning message in en.yml to give a strong message about what will happen when they hit delete.
In …
=> DEC-421: Add strong item delete warning

app/models/user.rb, app/services/map_user_to_api.rb, app/services/notify_error.rb, db/seeds.rb, spec/services/map_user_to_api_spec.rb, spec/services/notify_error_spec.rb
Fixes a bug where login could be blocked when an exception is encountered connecting to the API server. Also fixes #159
=> DEC-434 Fix for failed API call preventing logging in to the site

app/assets/javascripts/components/forms/FormErrorMsg.js.jsx, app/assets/javascripts/components/forms/FormServerErrorMsg.js.jsx, app/assets/javascripts/components/forms/ItemMetaDataForm.js.jsx, app/controllers/api_controller.rb, app/controllers/application_controller.rb, app/controllers/v1/items_controller.rb, spec/controllers/v1/items_controller_spec.rb
**Why:** Permissions check for editing the item was temporarily disabled, needed to be restored.
**How:** For the most part this was the same as any other permissions check, but we determined that there needed to be additional info in the response so that the front end could better report why the user received the response that it did. The ItemMetaDataForm already had mechanisms for rendering errors encountered with item validation. I expanded this to also handle generic server error messages and changed APIController to provide a permission error message when the user is forbidden to make the change.
=> DEC-327: Auth check v1 items update

app/controllers/v1/collections_controller.rb, spec/controllers/v1/collections_controller_spec.rb
Why: v1 collections publish/unpublish is currently not enforcing that the user have permission to edit the collection.
How: These actions now bail if the api renders a forbidden response.
=> DEC-425: Add permission check to collection publish/unpublish methods

app/assets/javascripts/components/CollectionPreviewModeToggle.js.jsx, app/assets/javascripts/components/CollectionPreviewPublish.js.jsx, app/assets/javascripts/components/publish/CollectionPublishToggle.js.jsx, app/controllers/v1/collections_controller.rb, app/queries/collection_query.rb, app/services/set_collection_preview_mode.rb, app/views/shared/_collection_left_nav.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20150616185505_add_preview_mode_to_collections.rb, db/schema.rb, spec/controllers/collections_controller_spec.rb, spec/controllers/v1/collections_controller_spec.rb, spec/models/collection_spec.rb, spec/queries/collection_query_spec.rb, spec/services/set_collection_preview_mode_spec.rb
**WHAT** Added functionality for managing a preview mode for collections. When preview mode is turned on, the collection remains hidden from the DEC home page but can be accessed via a direct URL.
**HOW** Added a service class to manage the preview mode attribute on collections, and added a new boolean field on collections. Added a react component for switching preview mode on and off. Modified the public_find() method for collection queries so that it accounts for the preview mode.
**WHY** We needed a way to enable preview mode so that the preview link on the admin interface would work, and to allow editors to share an accessible link with other individuals who are not editors so that they can view the work in progress prior to it being published.
=> Dec 407 collection preview

config/application.rb
Updating the browserify command so we can take adavantage of React 0.13+ ability to handle ES6 transformation.
https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html
=> Adding ES6 support

app/services/brood/collection.rb, app/services/brood/record.rb, app/services/brood/repo.rb, app/services/brood/set.rb, db/seeds.rb
This creates some seed data for development purposes.
I've tied the classes in to the `rake db:seed` task, but it could be made its own task if we wanted.
It pulls seed data from an external repo at https://github.com/ndlib/honeycomb-brood (so we don't have to store large files in this repo) and creates collections and items as defined in the repo.  It abuses the unique_id field to maintain its relationships, so urls on the front end wouldn't change after dropping/recreating the database.
It could also be updated *relatively* easily to add showcases/sections.
=> Advanced seed data using external repo

app/views/layouts/application.html.erb
The Roboto font is currently referenced via HTTP so it doesn't work when the environment is under HTTPS.
=> Fix the roboto font

app/assets/javascripts/components.js, app/assets/javascripts/components/forms/DateField.jsx, app/controllers/v1/items_controller.rb, app/decorators/v1/metadata_json.rb, app/validators/date_validator.rb, app/values/metadata_date.rb, spec/decorators/v1/metadata_json_spec.rb, spec/models/item_spec.rb, spec/validators/date_validator_spec.rb, spec/values/metadata_date/convert_to_iso_date_spec.rb, spec/values/metadata_date/convert_to_ruby_date_spec.rb, spec/values/metadata_date/format_display_text_spec.rb, spec/values/metadata_date_spec.rb
Why:  The code for validating dates and sending api response was both using the metadata_date model.  That model was incompatible with both operations in the case when data in the form was invalid.  This was because the we were relying on the failure of the metadata date to convert itself to a ruby date to raise exceptions.  This set of changes refactors that.  I also determined that the old storage format for dates caused a lot of extra code to be written so I refactored that as.
What:  I updated the way that date data is stored see: https://github.com/ndlib/honeycomb/wiki/Meta-Data-Storage  and how the date object will be sent in the api see: https://github.com/ndlib/honeycomb/wiki/Meta-Data-Api.   I also adjusted where the validations are happening and to stop relying on the metadata …
=> Immediate date fix

.gitignore, .rspec, Gemfile, Gemfile.lock, app/models/waggle/item.rb, app/models/waggle/sunspot/adapters/instance_adapter.rb, app/models/waggle/sunspot/adapters/item_data_accessor.rb, config/initializers/sunspot.rb, config/initializers/waggle.rb, config/sunspot.yml, solr/conf/admin-extra.html, solr/conf/elevate.xml, solr/conf/mapping-ISOLatin1Accent.txt, solr/conf/protwords.txt, solr/conf/schema.xml, solr/conf/scripts.conf, solr/conf/solrconfig.xml, solr/conf/spellings.txt, solr/conf/stopwords.txt, solr/conf/synonyms.txt, solr/solr.xml, spec/decorators/v1/metadata_json_spec.rb, spec/fixtures/v1/items/pig-in-mud.json, spec/models/waggle/item_spec.rb, spec/models/waggle/sunspot/adapters/instance_adapter_spec.rb, spec/models/waggle/sunspot/adapters/item_data_accessor_spec.rb, spec/rails_helper.rb, spec/services/destroy/exhibit_spec.rb, spec/support/solr_spec_helper.rb
This adds the Sunspot gem (for indexing content in Solr), creates an initial model for encapsulating the Item api data, and creates adapters for using Sunspot without ActiveRecord.
The Waggle::Item spec also includes an example of how we can approach  indexing and searching with Sunspot.
=> DEC-507 initial framework for indexing items

app/controllers/v1/search_controller.rb, app/decorators/v1/metadata_json.rb, app/models/waggle/search/hit.rb, app/models/waggle/search/query.rb, app/models/waggle/search/result.rb, app/views/v1/search/_hit.json.jbuilder, app/views/v1/search/index.json.jbuilder, config/routes.rb, config/sunspot.yml, spec/models/waggle/item_spec.rb
This adds a search API that is hopefully similar to what the final version will include.
http://localhost:3017/v1/collections/<collection.unique_id>/search?q=asdf&rows=3&start=6
The returned data should match https://github.com/ndlib/honeycomb/wiki/Search-Api
This is a stub that's connecting directly to ActiveRecord, but I am actively working on the Solr integration.  Since  the core search code will be changed drastically over the next couple days I have not added any tests for the ActiveRecord integration.
=> DEC-515 - initial search api stub

db/migrate/20150623132325_add_foreign_key_constraints.rb
Why: Current migration allowed for adding some foreign keys before breaking on others. This lead to a partially migrated state that was difficult to recover from.
How: Expanded the migration to first do checks for any records that would break the migration. If any fail, it will print the broken association and bail out of this and all future migrations. This should help us to isolate which tables we need to check whenever we deploy.
=> DEC-521: FK constraint checks

app/controllers/exhibits_controller.rb, app/decorators/v1/collection_json_decorator.rb, app/views/exhibits/_form.html.erb, app/views/v1/collections/_collection.json.jbuilder, db/migrate/20150804194246_add_show_page_title_to_exhibit.rb, db/schema.rb, spec/decorators/v1/collection_json_decorator_spec.rb, spec/models/exhibit_spec.rb
We don't have a way to control if we should show the site title as text in beehive this creates a way.
=> Add missing beehive title

app/values/cache_keys/custom/items.rb, spec/controllers/items_controller_spec.rb, spec/values/cache_keys/custom/items_spec.rb
Why: Item edit page is not updating the list of showcases if a user has previously visited the page
How: Added showcase list to cache key generation for item edit
=> DEC-540: Item showcase list caching bug

app/assets/javascripts/components/forms/ItemMetaDataForm.jsx, app/services/preprocess_image.rb, spec/services/preprocess_image_spec.rb
gifs were not being processed by vips.  we are now converting them to pngs first.
=> Fix vips gifs

app/assets/javascripts/components/forms/DateField.jsx
the bc check box was coming back always checked because the json boolean value is sent as "false" when it is passed through react_component.
=> fix date bc checked.

app/assets/javascripts/components/ShowcasesPanel.jsx, app/assets/stylesheets/ui-customizations.css.scss
Why: If an item belongs to a showcase that does not have a background image, it will fail to render the showcase list in the edit page for that item
How: Changed to use material ui avatars. Will use an avatar image if the showcase has a background image, and an avatar with the first letter of the showcase if it does not.
=> Showcase list bug

app/decorators/published_text.rb, app/views/collections/_list.html.erb, spec/decorators/published_text_spec.rb
it was always showing published changed to reflect a collections actual status
=> fix the status message on the collections listing page

app/views/sections/_show.json.jbuilder
Why: If a section is created in a showcase using an image, then the user changes that image, the section is not updated in the honeycomb showcase editor.
How: Changed the section to use the associated items image instead of the section image, since section.image is only ever touched when the section is first created.
=> Section does not show the correct image

app/assets/javascripts/components/ItemShowImageBox.jsx, app/decorators/item_decorator.rb, app/decorators/v1/item_json_decorator.rb, app/models/item.rb, app/services/save_honeypot_image.rb, app/services/save_item.rb, app/views/v1/items/_item.json.jbuilder, config/locales/en.yml, db/migrate/20150812192432_add_item_image_status.rb, db/schema.rb, spec/decorators/item_decorator_spec.rb, spec/decorators/v1/item_json_decorator_spec.rb, spec/models/item_spec.rb, spec/services/save_honeypot_image_spec.rb, spec/services/save_item_spec.rb
Why: Image processing is now performed in the background. When replacing an image in the item edit form, it loads the page before processing is performed and cannot render the image.
How: Modified the ItemShowImageBox to show an indeterminate progress circle until the image is finished processing. To do this it will make 3 calls, 5 seconds apart until it fails or receives an image_ready as the image_status, at which point it will render the image as before. This required several changes, including creating an image_status field on item and changing the data that is sent from the v1 api and the chain of calls prior to this component, such as the ItemJsonDecorator.
=> Replace image refresh bug

app/services/map_user_to_api.rb, spec/models/user_spec.rb, spec/services/map_user_to_api_spec.rb
Andy ran into an issue where a null values coming from the API set the user email address to null, violating the not null constraint on the user table.
We may also need to remove the not null constraint from the user table? (Or do that instead of this PR)
=> Fix for null data from the user api

app/views/showcases/_list.html.erb
no need for a published field and the preview link breaks the model of how preview is working in other parts of the site.
=> Update the showcase listing page

app/controllers/exhibits_controller.rb
because it was not in the allowed parameter list.
=> The Do not overlay site title over homepage image. was not saving 

app/assets/javascripts/components/showcase_editor/SectionImage.jsx
Don't render empty img tag when there is no image, render null instead.
=> Showcase text only section layout has width for image, looks bad.

app/assets/javascripts/components/forms/StringField.jsx
Fixed issue with form being marked as dirty whenever onblur was triggered on stringfields.
The only change other than adding newlines was removing `onBlur={this.handleChange}`
=> Item form marked as dirty when it should be clean

app/assets/javascripts/components/ReactDropzone.jsx
Turn the add items dialog into a modal so it can't be closed accidentally by clicking on the overlay
=> Dropzone modal

.travis.yml, spec/support/solr_spec_helper.rb
This adds travis notifications in our Hipchat room.  It will only notify when the build status changes.
I also moved the database migrate from `scripts` to `before_script`.  The reason for this is because travis will collapse the output from anything run in `before_script`.  Anything run in `scripts` won't be collapsed, and the migrate task is very verbose, leading to builds that are hard to read.
I also increased the time given for allowing Solr to start, since the original 10 seconds sometimes was not enough time for Travis to start Solr.
=> Travis CI notifications in Hipchat

app/models/collection.rb, app/models/item.rb, app/models/section.rb, app/models/showcase.rb, app/services/create_unique_id.rb, app/services/save_collection.rb, app/services/save_item.rb, app/services/save_section.rb, app/services/save_showcase.rb, spec/factories/collection.rb, spec/factories/item.rb, spec/factories/section.rb, spec/factories/showcase.rb, spec/services/create_unique_id_spec.rb, spec/services/save_collection_spec.rb, spec/services/save_item_spec.rb, spec/services/save_section_spec.rb, spec/services/save_showcase_spec.rb
Why: There was potential for records being created without a unique_id, causing lots of other problems since this is expected to be populated for all records.
How:
-Changed CreateUniqueId to no longer save the item
-Moved the generation of the id in the Save services to happen prior to the initial save
-Added validation on all of the models that have a unique_id since we never want any of these objects to be created without it
=> DEC-433: Records created without a unique_id

app/models/item.rb, app/services/save_item.rb, db/migrate/20150916134407_copy_items_unique_id_to_user_defined_id.rb, spec/services/save_item_spec.rb
Depends on https://github.com/ndlib/honeycomb/pull/240
Why: user_defined_id is now a required field, but the default path for creating items was not generating it.
How: Changed SaveItem to copy the unique_id into the user_defined_id field if it's not defined. If it is defined, such as through import, it will use the given id. The migration will do the same for records that already exist.
=> Dec 498 import migration

app/assets/javascripts/components/forms/HtmlField.jsx, app/assets/javascripts/redactor_field.js.coffee
Editing the source in an HTMLField component was yielding strange behaviors because the code was not updating the props with the raw user input.  Changed to use the raw user input in the onChange event on the textarea, and added separate functions for the callbacks from Redactor vs the textarea.
redactor_field.js.coffee: buttonSource is now just source in newer versions of Redactor.
=> DEC-574 fix redactor HTMLField component

app/controllers/import_controller.rb, app/services/google_create_items.rb, app/services/google_session.rb, app/views/import/_import_results.html.erb, app/views/import/import_google_sheet_callback.html.erb, config/locales/en.yml, spec/controllers/import_controller_spec.rb, spec/services/google_create_items_spec.rb, spec/services/google_session_spec.rb
Why: Need to validate all records and report back to the user meaningful information about the import
How: Refactored GoogleCreateItems and ImportController to provide more data about the valid/invalid records imported. GoogleCreateItems will now return a json with a summary and a list of errors. Created a basic view to show the data. This will likely move to a react component that can be displayed without leaving the items page (DEC-575) so I didn't spend a whole lot of time on its appearance.
Example of the results view:
=> DEC-529: import validation

app/models/metadata/configuration.rb, app/services/create_items.rb, app/services/find_or_create_item.rb, app/services/google_create_items.rb, app/services/rewrite_item_metadata.rb, app/views/import/_import_results.html.erb, db/migrate/20150918201430_add_unique_user_defined_id_constraint.rb, db/schema.rb, spec/models/item_spec.rb, spec/models/metadata/configuration_spec.rb, spec/services/create_items_spec.rb, spec/services/destroy/collection_spec.rb, spec/services/destroy/item_spec.rb, spec/services/find_or_create_item_spec.rb, spec/services/google_create_items_spec.rb, spec/services/rewrite_item_metadata_fields_spec.rb, spec/support/item_meta_helpers.rb
Why: Users would like imports to update existing items, not just create new ones
How: 
-Updated the services that create the items to do a find or create by user defined id and collection id. This meant having to also add a unique constraint on collection_id, user_defined_id in items since we are relying on this to uniquely identify items for imports. 
-Added an unchanged count to the summary to inform the user how many items matched up to existing records but were not changed.
=> DEC-499: Update items on import

app/services/create_unique_id.rb, app/services/create_user_defined_id.rb, app/services/save_item.rb, spec/services/create_items_spec.rb, spec/services/create_unique_id_spec.rb, spec/services/create_user_defined_id_spec.rb, spec/services/save_item_spec.rb
Why: We are currently unable to add more than one new item through the add items form in HoneyComb.
How:
-Problem was due to the fact that CreateUniqueId required an id for the object, which required saving the object to the database prior to calling this service class. Changed it to use SecureRandom.hex to generate a unique (enough) id, removing this dependence.
-Also changed the initial population of user_defined_id to be independent of the unique_id. It now has its own service class that generates an id using SecureRandom.hex. This one doesn't require as complex an id because it just needs to be unique within a collection.
-Also fixed a stubbed out test was that never implemented within create_items_spec and changed a few tests in save_item_spec to be more unit testish.
=> DEC-433: Add Item Bug

app/models/waggle/search/query.rb
12 makes a better default number because it breaks even if there are 4, 3 and 2 results per line.
=> changed the default search response rows.

app/models/waggle/metadata/value/date.rb, spec/models/waggle/adapters/solr/index/item_spec.rb, spec/models/waggle/adapters/solr/index/metadata_spec.rb, spec/models/waggle/metadata/value/date_spec.rb
Also change the metadata date indexer to not convert an iso date to a
date so it can be converted back to iso to be indexed.
=> fix bug with ruby's iso8601 parser.

app/assets/javascripts/components.js, app/assets/javascripts/components/GoogleExportButton.jsx, app/assets/javascripts/components/GoogleImportButton.jsx, app/assets/javascripts/mixins/GoogleCreatorMixin.jsx, app/controllers/export_controller.rb, app/models/metadata/configuration.rb, app/services/google_export_items.rb, app/services/google_session.rb, app/services/rewrite_item_metadata.rb, app/services/rewrite_item_metadata_for_export.rb, app/validators/date_validator.rb, app/values/metadata_date.rb, app/views/items/_action_bar.html.erb, config/routes.rb, spec/controllers/export_controller_spec.rb, spec/models/metadata/configuration_spec.rb, spec/services/google_export_items_spec.rb, spec/services/google_session_spec.rb, spec/services/rewrite_item_metadata_fields_spec.rb, spec/services/rewrite_item_metadata_for_export_spec.rb, spec/support/item_meta_helpers.rb, spec/values/metadata_date_spec.rb
Why: User needs a way to export a collection to a Google spreadsheet in the correct format
How: Added client side code that creates the spreadsheet then requests an auth token for access to the new sheet that the server can use to populate the data. Added routes/methods server side to export item data for a collection using the auth token and worksheet provided by the client. Once the export is complete the server will redirect the user to the new sheet.
Note: The google api does not currently allow programmatically setting a cells format. Because of this, by default, it will attempt to translate dates into a new format which will cause problems when reimporting. For the time being I'm using the old string literal trick (which google supports in its sheets) by prepending the value with a …
=> DEC-497: Export collection

app/decorators/item_decorator.rb, app/services/param_cleaner.rb, app/services/save_item.rb, spec/decorators/item_decorator_spec.rb, spec/services/param_cleaner_spec.rb, spec/services/save_item_spec.rb
Why: There is a difference between the item edit form and import in how they treat unset/empty metadata. This is causing import to report record changes when, from the user's perspective, there was no changes.
How:
-Modified item decorator to only send a metadata field if it actually has content. This is to prevent frontends from processing and sending update data for fields that actually have not been set.
-To catch any additional problems in the attribute data sent to SaveItem, added a ParamCleaner that does some common cleanup such as string bools to bools and empty string to nil
=> Import incorrectly showing updates

app/decorators/v1/collection_json_decorator.rb, app/views/v1/collections/_collection.json.jbuilder, spec/decorators/v1/collection_json_decorator_spec.rb
**What** Added additional type designation for collections output via the V1 API. Schema.org allows for an "additionalType" field which is typed as a URL. I also added definitions for the two new sub-types on the honeycomb wiki. I modified the parent context for collections to be "bib.schema.org" and changed the type to "Collection".
**Why** This gives the API consumer a way to easily identify what type of collection is being output. The "Collection" type, which is a sub-type of "CreativeWork" is also more appropriate for the type of things being output via the API in aggregate.
**What** Added a new method to the collection decorator, unit tests, and modified the jbuilder file as outlined above.
=> Add additional type designation in V1 output for collections

lib/tasks/adhoc_upload_images.rake
Why: Need a way to import images in bulk to support one-off collections that need to be created prior to supporting bulk image import through the interface.
How: Created a temporary rake task that we can use in the interim. It expects a collection id and a single text file with paths to the files that need to be imported on separate lines. It does not handle traversing directories to magically pull files in, so any collating of files will need to happen prior to the import when generating the text file.
=> Import images script

app/models/exhibition.rb
There don't seem to be any references to exhibit.name other than exhibition. Most objects are already using collection.name_line_1 and name_line_2.
=> DEC-615: Merge exhibit name into collection name_line_1, name_line_2

app/decorators/v1/collection_json_decorator.rb, app/models/exhibition.rb, db/migrate/20151009171750_migrate_descriptions_to_collections.rb, db/schema.rb, spec/decorators/v1/collection_json_decorator_spec.rb, spec/models/exhibition_spec.rb
**What**: Two description fields have been merged into the collection model and renamed to site_intro and short_intro to be consistent with how we're using them in the application.
**How**: Two fields were added to the collection model and the API was updated.
=> DEC-617 Merge description fields into collection model

app/decorators/v1/collection_json_decorator.rb, db/migrate/20151012194643_add_enable_browse_to_collections.rb, db/migrate/20151012201503_copy_enable_browse_from_exhibits_to_collections.rb, db/schema.rb, spec/decorators/v1/collection_json_decorator_spec.rb
-Created migrations to add enable_browse text column to Collections and copy existing data from the exhibits. enable_browse into collections. enable_browse
-Changed all references to exhibits. enable_browse to collections. enable_browse
=> DEC-630: Migrate enable_browse

app/decorators/v1/collection_json_decorator.rb, app/models/exhibition.rb, db/migrate/20151012145424_add_about_to_collections.rb, db/migrate/20151012145424_migrate_about_from_exhibits_to_collections.rb, db/migrate/20151012145430_copy_about_from_exhibits_to_collections.rb, db/schema.rb, spec/decorators/v1/collection_json_decorator_spec.rb
-Created migration to add about text column to Collections and copy existing data from the exhibits.about into collections.about
-Changed all references to exhibits.about to collections.about
=> DEC-625: Migrate about text to collections

app/decorators/v1/collection_json_decorator.rb, app/models/exhibition.rb, db/migrate/20151015142127_add_hide_title_to_collections.rb, db/migrate/20151015142141_copy_hide_title_from_exhibits_to_collections.rb, db/schema.rb, spec/decorators/v1/collection_json_decorator_spec.rb
-Created migrations to add hide_title_on_home_page column to Collections and copy existing data from the exhibits.hide_title_on_home_page into collections.hide_title_on_home_page
-Changed all references to exhibits.hide_title_on_home_page to collections.hide_title_on_home_page
=> DEC-632: Migrate hide title

app/decorators/v1/collection_json_decorator.rb, db/migrate/20151014135912_add_enable_search_to_collections.rb, db/migrate/20151014135926_copy_enable_search_from_exhibits_to_collections.rb, db/schema.rb, spec/decorators/v1/collection_json_decorator_spec.rb
-Created migrations to add enable_search text column to Collections and copy existing data from the exhibits.enable_search into collections.enable_search
-Changed all references to exhibits.enable_search to collections.enable_search
=> DEC-631: Migrate enable_search

config/settings.yml
What: Changes settings to that honeycomb points to collections.library.nd.edu as the beehive alias
=> Settings change for beehive alias

app/controllers/v1/pages_controller.rb, app/decorators/v1/collection_json_decorator.rb, app/decorators/v1/page_json_decorator.rb, app/decorators/v1/section_json_decorator.rb, app/decorators/v1/site_objects_json_decorator.rb, app/models/page.rb, app/values/cache_keys/custom/pages.rb, app/values/cache_keys/custom/v1_pages.rb, app/views/v1/items/_item.json.jbuilder, app/views/v1/pages/_page.json.jbuilder, app/views/v1/pages/index.json.jbuilder, app/views/v1/pages/show.json.jbuilder, app/views/v1/sections/_section.json.jbuilder, app/views/v1/showcases/show.json.jbuilder, config/routes.rb, spec/controllers/v1/pages_controller_spec.rb, spec/decorators/v1/collection_json_decorator_spec.rb, spec/decorators/v1/page_json_decorator_spec.rb, spec/decorators/v1/section_json_decorator_spec.rb, spec/decorators/v1/site_objects_json_decorator_spec.rb, spec/models/page_spec.rb, spec/values/cache_keys/custom/v1_pages_spec.rb
Why: Now that page models have been created, need a way to get page data via the api
How: 
-Added routes/controllers/views for v1 pages index and show
-Added cachekey generators for v1 pages index/show
-Changed showcases#show to use site objects for getting next/previous objects
-Added additionalType to item and section for consistency
Depends on https://github.com/ndlib/honeycomb/pull/291, will rebase when that's merged in.
=> DEC-652: Build pages api

app/controllers/v1/items_controller.rb, spec/controllers/v1/items_controller_spec.rb
Problem was due to the items controller not allowing arrays for some of the metadata fields that allow multiples. Fixed the items controller to allow arrays as params for all multiple fields. Also changed to permit user_defined_id to allow the user to change this if necessary.
=> DEC-684: Unable to save metadata

app/queries/showcase_query.rb, spec/queries/showcase_query_spec.rb
ShowcaseQuery will now add a default value for order that is based on the existing showcase orders when calling the build method. This should effectively append any new showcases to the end of the exhibit's list of showcases. Since it's done in the build method, the user has the ability to change it before saving the new showcase.
=> DEC-685: Showcase order default

app/models/waggle/item.rb, spec/models/waggle/adapters/solr/index/item_spec.rb, spec/models/waggle/item_spec.rb
Why: Related to https://docs.google.com/document/d/1yzEkvolhxhzUDvHD4y92hOvj-g4yx5lcgO7MeFJu0wU/edit#bookmark=id.8t3ocag3vsri
How: Beehive requires the medium url for search hits. Changed the waggle item. This change will require reindexing all items so that the new url is returned in search results.
Note: This PR is for a bug fix on 2.0. Ticket https://jira.library.nd.edu/browse/DEC-688 should address the problem in master.
=> BugFix: Search and Browse Stretched Images

config/environments/production.rb
API is currently using collections.library.nd.edu for things like showcases/items parts of collections, should be using honeycomb.library.nd.edu
=> Fix api url

.travis.yml, Gemfile, Gemfile.lock, app/queries/collection_query.rb, app/queries/section_query.rb, config/database.yml, db/dec_json_comparator.rb, db/dec_scraper.py, db/migrate/20150604150434_add_metadata_to_items.rb, db/migrate/20151014173751_copy_collection_id_to_showcase.rb, db/migrate/20151109212812_add_site_objects_to_collections.rb, db/pgloader.lisp, db/recreate_constraints.sql, db/schema.rb, spec/queries/collection_query_spec.rb
Why: We are going to be working on some features such as dynamic metadata that will be easier to r/w with postgres
How:
-Added pg gem to support postgres
-Fixed migrations and queries that explicitly used sql since there are differences between mysql/pg
-Fixed text type definitions, the pg equivalent of mysql longtext is just text
-Fixed travis to work with pg
-Found a problem with the section query and changed to work a little more safely with both pg and mysql
-Found a problem with ordering differences between postgres and mysql. Changed the default order of collections to force it to match the way mysql collections were ordered.
Specific to server migration:
-Created a pgloader script to use to copy the data. Had to make it only copy data to avoid it writing the schema differently from …
=> DEC-674: Migrate developers to postgres

app/queries/site_objects_query.rb, spec/queries/site_objects_query_spec.rb
Why: Within Page/Showcase edit, the delete button tries to disable itself if the object is included in site_objects, as a way of enforcing referencial integrity at the app layer. This check fails when the field is nil.
How: Changed the site objects query object to return an empty array if the field is null or empty string.
=> DEC-696: Page/Showcase edit fails to load when site objects is nil

app/controllers/v1/items_controller.rb, spec/controllers/v1/items_controller_spec.rb
Why: The page redactor allows the user to insert images that are in the collection, but this fails if the collection is not either in preview mode or is published.
How: Modified ItemsController#index to use any_find instead of public_find, so that we can get items for the collection even if it's not published/preview enabled.
=> DEC-695: Cannot insert items into page if collection is not published or preview enabled

.travis.yml, app/models/item.rb, db/migrate/20160121133856_migrate_item_metadata_to_jsonb.rb, db/schema.rb
why: now that the we have jsonb. we need to migration of the old json store of metadata values to the new and flashy jsonb fields. 
what: added a migration to convert the field and converted the class.
=> Dec 738 migrate metadata to jsonb

app/models/collection.rb, app/models/collection_configuration.rb, app/services/create_collection_configuration.rb, app/services/save_collection.rb, db/migrate/20160121193224_create_metadata_configurations.rb, db/migrate/20160122191511_update_collection_configuration.rb, db/schema.rb, spec/factories/item.rb, spec/models/collection_configuration_spec.rb, spec/models/collection_spec.rb, spec/models/item_spec.rb, spec/services/create_collection_configuration_spec.rb, spec/services/save_collection_spec.rb
Why:  Config needs to be stored in the database.  
What:  Updated to auto generate the configuration when a collection is created and to store it in the database.
=> Dec 739 create collection metadata config

npm-shrinkwrap.json, package.json
Why: Build is currently broken because of fsevents dependency. 
How: fsevents is a dep of gulp-watch. We don't need gulp in honeycomb. Removed from package.json and regenerated the shrinkwrap.
=> Fix travis build

app/models/waggle/item.rb, spec/models/waggle/adapters/solr/index/item_spec.rb, spec/models/waggle/item_spec.rb
Similar to https://github.com/ndlib/honeycomb/pull/298, this is to patch master.
Note again, this will require reindexing all of your items so that the medium url is returned in search results (rake search:index_all).
=> DEC-774: Bugfix stretched images in search/browse

app/assets/javascripts/components/forms/ItemMetaDataForm.jsx, app/assets/javascripts/components/forms/ItemMetaDataSelectAdditionalFields.jsx
Why: Drop down box for adding new metadata has disappeared from the item form.
How: Readded the ItemMetadataSelectAdditionalFields to the metadata form. Looks like it may have been removed by accident during the mui update.
=> DEC-773: Add metadata drop down doesn't appear

app/assets/javascripts/components/forms/SitePath.jsx, app/controllers/collections_controller.rb, app/controllers/v1/collections_controller.rb, app/decorators/v1/page_json_decorator.rb, app/queries/site_objects_query.rb, app/values/cache_keys/custom/v1_collections.rb, app/views/collections/_site_path_form.html.erb, app/views/v1/collections/site_path.json.jbuilder, config/routes.rb, db/dec_scraper.py, db/migrate/20160208151649_rename_site_objects_to_site_path.rb, db/schema.rb, spec/controllers/v1/collections_controller_spec.rb, spec/decorators/v1/page_json_decorator_spec.rb, spec/decorators/v1/showcase_json_decorator_spec.rb, spec/queries/page_query_spec.rb, spec/queries/showcase_query_spec.rb, spec/queries/site_objects_query_spec.rb, spec/values/cache_keys/custom/v1_collections_spec.rb
Why: Before I can work on beehive, we need to change site_objects to site_path in honeycomb.
How: Migrated site_objects to site_path and updated all references to site_path.
Renamed branch from https://github.com/ndlib/honeycomb/pull/319
=> DEC-662: Update beehive work with site_path

app/assets/javascripts/actions/MetaDataConfigurationActions.js, app/assets/javascripts/components/forms/DateField.jsx, app/assets/javascripts/components/forms/ItemMetaDataForm.jsx, app/assets/javascripts/components/forms/MetaDataFieldDialog.jsx, app/assets/javascripts/components/forms/MetadataConfigurationForm.jsx, app/assets/javascripts/stores/MetaDataConfigurationStore.js, app/controllers/v1/items_controller.rb, app/controllers/v1/metadata_fields_controller.rb, app/models/metadata/configuration.rb, app/models/metadata/configuration/field.rb, app/models/waggle.rb, app/services/create_collection_configuration.rb, app/services/metadata/configuration_input_cleaner.rb, app/services/metadata/create_configuration_field.rb, app/services/metadata/update_configuration_field.rb, app/services/metadata_input_cleaner.rb, spec/controllers/v1/items_controller_spec.rb, spec/controllers/v1/metadata_fields_controller_spec.rb, spec/models/metadata/configuration_spec.rb, spec/services/metatdata/configuration_input_cleaner_spec.rb, spec/services/metatdata/create_configuration_field_spec.rb
Allow the creation of metadata fields.  
1.  Updates to the form to create fields.
2.  Added a parameter normalizer to ensure data is saved correctly. 
3.  Added routes and services to create
=> Dec 766 allow metaconfig to be created

app/assets/javascripts/actions/MetaDataConfigurationActions.js, app/assets/javascripts/components/forms/ItemMetaDataForm.jsx, app/assets/javascripts/components/forms/MetadataConfigurationForm.jsx, app/assets/javascripts/stores/MetaDataConfigurationStore.js, app/decorators/v1/metadata_json.rb, app/models/metadata/configuration.rb, app/models/metadata/configuration/facet.rb, app/models/metadata/configuration/field.rb, app/models/metadata/configuration/sort.rb, app/models/waggle.rb, app/models/waggle/adapters/solr/search/facet.rb, app/models/waggle/search/result.rb, app/models/waggle/search/sort_field.rb, app/views/collections/settings.html.erb, app/views/layouts/application.html.erb, app/views/v1/search/index.json.jbuilder, config/metadata/item.yml, spec/decorators/v1/metadata_json_spec.rb, spec/models/metadata/configuration/facet_spec.rb, spec/models/metadata/configuration/field_spec.rb, spec/models/metadata/configuration/sort_spec.rb, spec/models/metadata/configuration_spec.rb, spec/models/waggle/adapters/solr/search/facet_spec.rb, spec/models/waggle/search/result_spec.rb, spec/models/waggle/search/sort_field_spec.rb
Why: User needs a way to remove and restore removed fields from their configuration, except for necessary fields like name.
How: 
- Added an "active" property to all fields. 
- Changed the configuration form to a list with a button that allows them to remove/restore each field. 
- Added an immutable property list to each metadata field that allows us to restrict what properties a user can change. Ex: for the name field, active is now an immutable property.
- Changed item api to filter out metadata fields that are inactive.
- Changed search to filter out inactive fields from facets and sorts.
=> DEC-796: User would like to remove/restore metadata fields

config/metadata/vatican_item.yml
I added an example vaitcan metadata file.  This file can be loaded into your collections metadata. 
It is required if you want to use any of the new pulls for zucchetto.
I imagine this file will change over time as we work through the development of zucchetto.  
To load:
```
collection_configuration = Collection.first.collection_configuration
config = YAML.load_file(Rails.root.join("config/metadata/", "vatican_item.yml"))
collection_configuration.metadata = config[:fields]
collection_configuration.save! 
```
=> add file for vatican only metadata

app/models/metadata/fields/date_field.rb, app/services/find_or_create_item.rb, app/services/google_export_items.rb, app/services/metadata_input_cleaner.rb, app/services/param_cleaner.rb, app/services/rewrite_item_metadata.rb, app/services/rewrite_item_metadata_for_export.rb, spec/models/metadata/fields/date_field_spec.rb, spec/services/find_or_create_item_spec.rb, spec/services/google_export_items_spec.rb, spec/services/metadata_input_cleaner_spec.rb, spec/services/param_cleaner_spec.rb, spec/services/rewrite_item_metadata_fields_spec.rb, spec/services/rewrite_item_metadata_for_export_spec.rb
Why: Lots of changes to the way metadata is handled to accommodate the dynamic metadata, which broke export/import.
How: User defined id is no longer part of metadata, but is still needed for export/import. Added special handling to merge this with meta fields. Changed the parsing/rewriting now that all metadata will be stored as arrays. Changed import to use the new metadata setter service to assign metadata to the items. Also fixed a problem associated with postgres' ordering of keys that caused imports to appear as though an item changed when it had not (See DEC-812 for more info).
=> DEC-801: Fix export import

app/models/metadata/configuration/field.rb
Fixed a comparison problem with convert_strings_to_boolean. If the kvp was already converted (ex: it went through ConfigurationInputCleaner), then the == "true" would fail for true values, and convert it to false
=> DEC-832: Reactivate a metadata field fails

app/assets/javascripts/actions/MetaDataConfigurationActions.js, app/assets/javascripts/components/forms/MetaDataFieldDialog.jsx, app/controllers/v1/metadata_fields_controller.rb, app/models/metadata/configuration/field.rb, app/services/metadata/configuration_input_cleaner.rb, spec/controllers/v1/metadata_fields_controller_spec.rb, spec/models/metadata/configuration/field_spec.rb, spec/models/metadata/configuration_spec.rb, spec/services/metatdata/configuration_input_cleaner_spec.rb
Why: After making a change (such as deactivating) a configuration field, subsequent calls to create a new field would fail.
How: 
-The configuration properties "boost" and "order" are assumed to be integers, but the config update is receiving these as strings. Changed the input cleaner to convert stringified integers such as "15", but not things like "15abc". 
-Changed the validation to ensure boost and order are integers. This way if anything gets passed other than a basic integer that's been stringified, it will throw a validation error back to the app that posted the update.
-Separated create/update actions so that create can stop passing values for the properties that have none, this way the api can properly perform validation on all data passed in.
=> DEC-835: Cannot create new metafield

app/views/collections/_general_settings_form.html.erb, app/views/collections/_general_settings_subform.html.erb, app/views/collections/new.html.erb
Refactored the pieces that were shared between the new collection form and the general settings form into its own partial and changed those two forms to render that partial. This structure changed when we added subforms to settings to accommodate the metadata configuration.
=> DEC-829: Creating a new collection fails

app/services/destroy/collection.rb, app/services/destroy/collection_configuration.rb, spec/controllers/admin/external_collections_controller_spec.rb, spec/controllers/collections_controller_spec.rb, spec/factories/collection_configuration.rb, spec/services/destroy/collection_configuration_spec.rb, spec/services/destroy/collection_spec.rb
Why: Throws an exception due to foreign key constraint on the associated collection configuration.
How: Added a destroy service for collection config and changed DestroyCollection to use this new service to delete the associated config on cascade delete.
=> DEC-815: Cannot delete a collection

app/assets/javascripts/imagemanager.js
DEC-864:
-Temporarily disabled the ability to shortcut creating items via the insert image tool. This does not work correctly when background processing is enabled.
DEC-840:
-Also found a fix to the redactor reverting the changes after inserting an image. The insert.html seems to work better, and there were a few calls that insert.node was missing compared to insert.html.
=> DEC-864, DEC-840: Cannot insert image into page

app/models/waggle/adapters/solr/search/result.rb, solr/configsets/honeycomb/conf/solrconfig.xml, spec/models/waggle/adapters/solr/search/result_spec.rb
Changes the Query Parser to edismax which lets us use and AND and OR.   
Also it is in 2 places eventually I would remove the call in the Result Class eventually.  It allows me to switch the query type with out restarting solr which is currently a little bit of a pain.
=> Update solr query parser

app/models/waggle/adapters/solr/search/result.rb, solr/configsets/honeycomb/conf/solrconfig.xml, spec/models/waggle/adapters/solr/search/result_spec.rb
Why: For our purposes, search needs to default to OR when given terms separated by space.
How: Changed the mm param to solr to 1. This effectively works as an OR operator between optional terms. Things like +term or -term, or "term AND term" are all still obeyed.
For more info on the mm param, see: [The mm (Minimum Should Match) Parameter](https://cwiki.apache.org/confluence/display/solr/The+DisMax+Query+Parser#TheDisMaxQueryParser-Themm(MinimumShouldMatch)Parameter)
=> DEC-913: Change default search to OR (3.0)

app/models/waggle/adapters/solr/search/result.rb, solr/configsets/honeycomb/conf/solrconfig.xml, spec/models/waggle/adapters/solr/search/result_spec.rb
Why: For our purposes, search needs to default to OR when given terms separated by space.
How: Changed the mm param to solr to 1. This effectively works as an OR operator between optional terms. Things like +term or -term, or "term AND term" are all still obeyed.
For more info on the mm param, see: [The mm (Minimum Should Match) Parameter](https://cwiki.apache.org/confluence/display/solr/The+DisMax+Query+Parser#TheDisMaxQueryParser-Themm(MinimumShouldMatch)Parameter)
=> DEC-913: Change default search to OR (master)

app/assets/javascripts/application.js, config/boot.rb, package.json
What: A bug was discovered related to the use of the Axios javascript library, only on IE and specifically IE 11. IE does not recognize the Promise object as having been defined.
How: Added a new module to NPM called 'es6-promise', which provides a polyfill back port that forces IE 10 and later to recognize the Promise definition.
**Note**: IE 10 and later also no longer recognize the comment conditionals (e.g. '[if IE]') so compensating javascript can no longer be included in the head of the document to correct IE compatibility issues
**ALSO**: Added an override to force Webrick to bind to IP address 0.0.0.0 to make it easier to debug from local VMs accessing Webrick running in the native OS
=> Dec 925 fix for promise bug

app/assets/javascripts/components/forms/ExternalCollectionForm.jsx, app/controllers/admin/external_collections_controller.rb, app/views/admin/external_collections/_form.html.erb, app/views/admin/external_collections/_list.html.erb
What: The attributes for collections and thus external collections changed and the description attr was deprecated. That needed to be corrected for the related forms and lists to work related to external collections.
How: I changed the attribute reference to 'about' instead of 'description' and updated the appropriate code and view pages to reflect that.
=> DEC-934 Fix for changed external collection attr

lib/tasks/adhoc_upload_images.rake
Changed to replace the images of items that have the same name as that image (such as from a previous import)
=> DEC-947: Change rake task to replace existing images

app/assets/javascripts/components/forms/MetaDataConfigurationForm.jsx
What: There is a bug related to Safari in material-ui that short circuits the on click events for certain components and forces the user to click the element twice for the event to fire.
How: Instead of using onClick(), I changed the component in question so that it uses onMouseDown() coupled with onTouchStart() for touch screen devices.
=> DEC-928 Fix for Safari onClick bug for metadata button

npm-shrinkwrap.json
Adding es6 to shrinkwrap. Was added to package in PR 355 without updating shrinkwrap.
=> DEC-925: Shrinkwrap es6

app/services/save_honeypot_image.rb, spec/services/save_honeypot_image_spec.rb
Added special handling of items after a honeypot job successfully saves. It will now reindex the item since the indexed doc depends on the thumbnail generated by honeypot.
=> DEC-950 (Master): Creating a new item does not show thumbnail on search

app/services/save_honeypot_image.rb, spec/services/save_honeypot_image_spec.rb
Added special handling of items after a honeypot job successfully saves. It will now reindex the item since the indexed doc depends on the thumbnail generated by honeypot.
=> DEC-950 (v3.0): Creating a new item does not show thumbnail on search

app/decorators/collection_image.rb, spec/decorators/collection_image_spec.rb
Problem was with how it was finding a thumbnail to use, not the item count. Changed it to use the collection image if it has one. If none is available, it will find the first item that has a honeypot image via a query instead of a block test.
=> DEC-648: Honeycomb collection list with large collections is slow

app/decorators/collection_image.rb, spec/decorators/collection_image_spec.rb
Problem was with how it was finding a thumbnail to use. Changed it to use the collection image if it has one. If none is available, it will find the first item that has a honeypot image via a query instead of a block test.
=> DEC-648 (v3.0): Honeycomb collection list with large collections is slow

app/values/cache_keys/custom/v1_items.rb, spec/controllers/v1/items_controller_spec.rb, spec/values/cache_keys/custom/v1_items_spec.rb
What: Cache was persisting for items when metadata fields were changed at the collection level. The metadata configuration was added as a changeable object to the item level caching methods on the V1 API.
How: Added the configuration as a potential mutable object in generating the cache keys. Also updated tests to account for the presence of the collection_configuration() on collection objects.
=> Dec 927 fix cache expiration metadata fields

app/values/cache_keys/custom/v1_pages.rb, app/values/cache_keys/custom/v1_sections.rb, app/values/cache_keys/custom/v1_showcases.rb, spec/controllers/v1/pages_controller_spec.rb, spec/controllers/v1/sections_controller_spec.rb, spec/controllers/v1/showcases_controller_spec.rb, spec/values/cache_keys/custom/v1_pages_spec.rb, spec/values/cache_keys/custom/v1_sections_spec.rb, spec/values/cache_keys/custom/v1_showcases_spec.rb
Page/Section/Showcase#show all also render item metadata, so they need to check the metadata configuration id/updated_at when generating etag.
=> DEC-927: Metadata field cache bug

app/assets/javascripts/components/search/SearchPage.jsx
Changed the item listing to use the tag icon (https://design.google.com/icons/#ic_local_offer) when no image is present to signify that the item will only render metadata tags.
=> DEC-1050: Metadata only icon

app/models/metadata/configuration/facet.rb, app/models/waggle/adapters/solr/search/result.rb, spec/models/metadata/configuration/facet_spec.rb, spec/models/waggle/adapters/solr/search/result_spec.rb
We can customize facets for any client by modifying the configuration, but currently we had no way to customize the limits that are used when displaying each facet. Changed the facet object to allow specifying a limit per facet. If none is found, it will fall back to the default in the solrconfig.xml
=> DEC-1039: Custom facets

app/models/waggle/search/query.rb, spec/models/waggle/adapters/solr/search/result_spec.rb, spec/models/waggle/search/query_spec.rb
Why: User would like to be able to specify custom sort options, including different directions for the same field.
How: Had to reinstate the config field lookups in the sort field and sort direction calls. This will allow specifying different directions for each sort option to use by default, ex: sort name asc, but date desc. This only comes into play when the caller does not specify a direction param. If a direction is not present in the params, or the config, it will fall back to "desc" to match the default solr behavior.
=> DEC-1040: Custom sorts

app/assets/javascripts/components/forms/ItemMetaDataForm.jsx, app/controllers/v1/metadata_controller.rb, app/decorators/item_decorator.rb, app/models/item.rb, app/models/metadata/configuration.rb, app/services/save_item.rb, app/services/save_metadata.rb, app/validators/metadata_validator.rb, app/views/v1/metadata/errors.json.jbuilder, app/views/v1/metadata/update.json.jbuilder, config/routes.rb, spec/controllers/v1/metadata_controller_spec.rb, spec/decorators/item_decorator_spec.rb, spec/models/item_spec.rb, spec/services/save_item_spec.rb, spec/services/save_metadata_spec.rb, spec/validators/metadata_validator_spec.rb
Why: the current implementation was validating the metadata on create which was causing new item creation to fail also there was a bug with the custom metadata validator in that it always used the first loaded collection configuration to validate agains.
What:  I separated the routes for updating items and metadata.  All routes to items should only save item data.  There is a new api route v1/items/ID/metadata that saves the metadata.   There is also a new save_metadata class for saving metadata.  
SaveItem no longer saves metadata.
=> Dec 1064 update item metadata saving

app/assets/javascripts/components.js, app/assets/javascripts/components/search/SearchPage.jsx, app/assets/javascripts/components/search/SearchPagination.jsx
Why: Cannot see items for a collection in Safari
How: Problem was with material-ui Table. Symbol is undefined. We're pretty close to a deployment so I don't want to go through updating react and material-ui just to fix this, defined Symbol instead, see https://github.com/callemall/material-ui/issues/1531. Also fixed a problem with passing the key prefix to the pagination component. this.props.key was deprecated, need to pass as a different prop.
=> DEC-624: Bugfix item list on Safari

app/controllers/collections_controller.rb
Bug: Custom slug updates via the UI were failing
Fix: Thought that this was related to caching but it ended up being related to the permitted save params. This was due to changes in the model and removing the custom_slug method earlier. Adding url_slug to the permitted params list resolved the issue.
=> DEC-1069 Fix for custom slug update

app/services/create_beehive_url.rb, spec/services/create_beehive_url_spec.rb
Bug: Preview link was broken because of missing forward slash
Fix: I put the forward slash back in, but as a caveat, I previously needed to take the slash out because it was rendering a double forward slash - which broke the preview link as well
=> DEC-1071 Fix broken preview link

app/services/brood/collection.rb
the save_metadata update broke this.  Now it is fixed.
=> fix db:seed data

app/services/create_url_slug.rb, spec/services/create_url_slug_spec.rb
What: CreateURLSlug was returning "name" when no value was supplied. This caused a bug for the custom slug functionality.
Fix: Changed the CreateURLSlug class so that it returns nil if no value is supplied, and modified the associated spec.
=> DEC-1090 Fix for custom slug bug

app/services/metadata/create_configuration_field.rb, app/services/metadata/generate_unique_key.rb, spec/services/metatdata/create_configuration_field_spec.rb, spec/services/metatdata/generate_unique_key_spec.rb
What: Implemented a fix for condition when curator creates a duplicate metadata field
Fix: Created a class that generates a uuid that will be assigned to every custom metadata field. This avoids the problem of having truly duplicate fields, but does not address the possibility that a curator will create two metadata fields with the same label which presents a problem for serializing collections from the API. That will need to be addressed in another ticket.
=> DEC-841 Fix for creating metadata fields with same label / name

app/assets/javascripts/actions/MetaDataConfigurationActions.js, app/services/metadata/create_configuration_field.rb, spec/services/metatdata/create_configuration_field_spec.rb
What: This is part 2 of the fix for entering a duplicate metadata field in the collection configuration. This PR addresses the potential problem of a curator entering in a duplicate metadata label.
Fix: Added a method to check for a duplicate label value against all of the extant metadata fields. It reports back with a true or false. create_field() in CreateConfigurationField now has a conditional to test for the duplicate label and returns nil if the entered parameter is a duplicate. The standard controller behavior was left untouched.
=> DEC-1093 Prevent duplicate metadata label data entry

Gemfile.lock, app/decorators/collections_side_nav.rb, spec/decorators/collections_side_nav_spec.rb
Added homepage as the default active option upon entry to Site Setup page.
Added code into collections_side_nav.rb to set returned value to "active" for homepage as a default option. This is used in the _site_nav partial to set the class value.
=> Set homepage as active option on Site Setup page

app/assets/stylesheets/nav_bar.css.scss, app/controllers/collections_controller.rb, app/decorators/collections_side_nav.rb, app/decorators/v1/collection_json_decorator.rb, app/views/collections/_collection_introduction_form.html.erb, app/views/collections/_side_nav.html.erb, app/views/layouts/application.html.erb, app/views/v1/collections/_collection.json.jbuilder, config/locales/en.yml, config/routes.rb, db/migrate/20160706194509_remove_site_intro_from_collections.rb, db/schema.rb, spec/decorators/collections_side_nav_spec.rb, spec/decorators/v1/collection_json_decorator_spec.rb, spec/models/collection_spec.rb
Removed ND/Library brand bar HTML and CSS from honeycomb.
Rebased on top of DEC-1103 due to schema conflict with deleted site_intro field.
=> Dec 1132 remove brand bar on honeycomb

app/controllers/collections_controller.rb, app/decorators/collections_side_nav.rb, app/decorators/v1/collection_json_decorator.rb, app/views/collections/_collection_introduction_form.html.erb, app/views/collections/_side_nav.html.erb, app/views/v1/collections/_collection.json.jbuilder, config/locales/en.yml, config/routes.rb, db/migrate/20160706194509_remove_site_intro_from_collections.rb, db/schema.rb, spec/decorators/collections_side_nav_spec.rb, spec/decorators/v1/collection_json_decorator_spec.rb, spec/models/collection_spec.rb
Migrate database to remove site_intro column from collections. Removed the collection introduction form and related routes, as well as all other references to site_intro.
=> Dec 1103 remove the ui and database field to create introductions

app/services/create_beehive_url.rb, app/views/shared/_collection_left_nav.html.erb, spec/services/create_beehive_url_spec.rb
Bug: The preview links on the item edit and showcase edit pages were broken when a custom slug was established. The preview links tried to use the custom url as the base url for the preview.
Fix: Added a flag in the method call for CreateBeehiveURL that will output the custom url if the flag is set to true; by default the flag is set to false, and it's an optional parameter for the call() method.
=> DEC-1101 Fix for preview link urls

app/views/collections/_side_nav.html.erb, app/views/collections/new.html.erb, app/views/collections/site_setup.html.erb, app/views/editors/index.html.erb, app/views/pages/new.html.erb, app/views/showcases/new.html.erb
Remove panels and add standard heading styles for Site Setup and Editors pages. 
Rename title on setup sidebar to be consistent with main menu option name.
Corresponds to JIRA tasks DEC-1138 and DEC-1139.
=> Standardize page styles for editors and setup

app/assets/javascripts/components/forms/ExternalCollectionForm.jsx, app/assets/javascripts/components/user_panel/UserPanel.jsx, app/views/admin/external_collections/edit.html.erb, app/views/admin/external_collections/new.html.erb, app/views/collections/site_setup.html.erb, app/views/pages/edit.html.erb, app/views/pages/new.html.erb, app/views/shared/_error_messages.html.erb, app/views/showcases/new.html.erb, config/locales/en.yml
- Remove gray panels on remaining pages to standardize site format. 
- Correct misspelling in error message. 
- Correct back arrow paths on add pages and add showcases. 
- Add missing titles in en.yml to show on tabs and for page titles.
This is a continuation of DEC-1138 and DEC-1139... as I was making those changes, I also changed add and edit pages but missed a couple. 
This also includes item DEC-1141, a bug caused by the changes in DEC-1138.
=> Standardize honeycomb pages

app/services/create_items.rb, app/services/find_or_create_item.rb, spec/services/create_items_spec.rb, spec/services/find_or_create_item_spec.rb, spec/services/google_create_items_spec.rb
Bug: Import routine was raising exception when name was missing from import spreadsheet
Fix: Added check for the validity of item metadata since the name property was moved into the metadata attribute
=> DEC-1148 Fix for missing name import bug

app/assets/javascripts/components/ItemShowImageBox.jsx
Bug: Image processing status was not being determined properly due to status changes made when images were separated from items, leaving the item image box in a limbo state when an image was replaced.
Fix: I put the correct status strings into the ItemShowImageBox component and that resolved the issue.
=> DEC-1164 Initial fix for image processing bug

app/decorators/v1/item_json_decorator.rb, app/models/collection.rb, app/models/image.rb, app/models/item.rb, app/models/media.rb, app/models/page.rb, app/models/showcase.rb, app/services/find_or_create_image.rb, db/migrate/20160718190411_add_media_to_image.rb, db/migrate/20160718193812_copy_image_fields_to_data.rb, db/migrate/20160720142311_archive_image_media_fields.rb, db/migrate/20160720143041_change_image_to_media.rb, db/schema.rb, spec/models/image_spec.rb, spec/models/media_spec.rb, spec/services/find_or_create_image_spec.rb, spec/services/save_collection_spec.rb
This changes the Image model into a more general Media model with a type and json data field to store the information about the image media. This will be used to also store other media types such as audio and video. This does not implement the actual Audio or Video models.
=> DEC-1153: Add media to database

app/models/audio.rb, app/models/image.rb, app/models/media.rb, app/models/video.rb, db/migrate/20160805193022_add_unique_id_to_media.rb, db/migrate/20160805194419_assign_media_unique_ids.rb, db/schema.rb, lib/store_enum.rb, spec/models/audio_spec.rb, spec/models/image_spec.rb, spec/models/media_spec.rb, spec/models/video_spec.rb
This adds the Audio and Video models. I ended up making our own version of enum that works with store_accessors now that we have 3 different entities each with their own state system. It works just like rails enum, except you can pass a store accessor so that the enum value will be stored in that store instead of on the base of the model.
=> DEC-1156: Create audio video models

Gemfile, Gemfile.lock, app/services/save_honeypot_image.rb, app/services/save_media_thumbnail.rb, config/settings.yml, spec/fixtures/buzz_response.json, spec/services/save_honeypot_image_spec.rb, spec/services/save_media_thumbnail_spec.rb
**Goal**: Add functionality that supports adding a thumbnail / still image for a media file (audio or video).
**Work**: Implemented new service class, renamed some methods to make them more generic, and added configs
=> DEC-1115 Add thumbnail create / update for media

app/controllers/v1/media_controller.rb, app/queries/media_query.rb, app/services/finish_media_upload.rb, config/routes.rb, spec/controllers/v1/media_controller_spec.rb, spec/queries/media_query_spec.rb, spec/services/finish_media_upload_spec.rb
This PR does not cover post back to buzz if we decide to do the post back.   It only covers moving the state from allocated to ready.  We will need to discuss if we wish for post back to happen.  DEC-1175 references dealing with the buzz side of the transaction.  
Added an action to finish upload at 
/v1/media/#id/finish_upload. 
Added service class to perform the transition
Added Query object for media.
=> Dec 1174  Action to finish uploading an image

app/controllers/v1/media_controller.rb, app/errors/buzz/internal_server_error.rb, app/errors/buzz/unprocessable_entity.rb, app/models/audio.rb, app/models/video.rb, app/services/allocate_s3_url.rb, app/services/buzz_media.rb, app/services/finish_media_upload.rb, app/services/save_media_thumbnail.rb, app/services/serialize_new_s3_media.rb, config/application.rb, spec/controllers/v1/media_controller_spec.rb, spec/models/audio_spec.rb, spec/models/video_spec.rb, spec/services/allocate_s3_url_spec.rb, spec/services/buzz_media_spec.rb, spec/services/finish_media_upload_spec.rb, spec/services/save_media_thumbnail_spec.rb, spec/services/serialize_new_s3_media_spec.rb
Adds an action that will create the media object on Buzz. This will typically be called once the user has finished uploading to the designated s3 location. To do this I added a service class that will ideally handle all of the communication to the Buzz server and refactored the save_media_thumbnail service to use this instead of directly handling this communication.
=> Post to Buzz

app/services/allocate_s3_url.rb, config/settings.yml, spec/services/allocate_s3_url_spec.rb
Changed the s3 url signing to read the credentials from the aws prescribed shared location and moved remaining settings out of secrets.
=> Read credentials from aws config

app/models/waggle/adapters/solr/search/result.rb, config/style_guides/.ruby-style.yml, spec/models/waggle/adapters/solr/search/result_spec.rb
DEC-1133
Tags selected in the UI were sometimes not returned in the results, and thus could not be rendered in the UI - making it impossible to deselect them.
I added a new query that _only_ retrieves these tag values, no results, and appends the tags to the tag list if not already present.
=> Selected tags sometimes were not returned

app/assets/javascripts/components/PagesPanel.jsx, app/assets/javascripts/components/ShowcasesPanel.jsx, app/assets/javascripts/components/showcase_editor/ShowcaseEditorTitle.jsx, app/decorators/showcase_decorator.rb, app/decorators/v1/showcase_json_decorator.rb, app/views/showcases/show.json.jbuilder, spec/decorators/showcase_decorator_spec.rb, spec/decorators/v1/showcase_json_decorator_spec.rb
If a Page had an associated background image that was stuck in a "not ready" state, it would fail to render the associated pages. Found this to also occur for Showcases.
Summary of changes:
- Changed PagesPanel to not attempt to render an image if it's not ready to be rendered.
- The json renderers for Showcases were not following the same serialization path as in Pages/Items so the image status was not readily available. So in order to fix the ShowcasesPanel, and make things more consistent, I had to change the showcase json decorators to use the SerializeMedia service.
- ShowcaseEdtorTitle previously assumed that props.showcase.image would always contain a valid url (rendered by app/decorators/showcase_decorator#honeypot_image_url). This caused unnecessary calls to load an invalid image …
=> Bugfix: Item not showing associated Pages when trying to delete

app/assets/javascripts/components/PagesPanel.jsx, app/assets/javascripts/components/ShowcasesPanel.jsx, app/controllers/pages_controller.rb, app/controllers/sections_controller.rb, app/controllers/showcases_controller.rb, app/decorators/showcase_decorator.rb, app/views/pages/_list.html.erb, app/views/showcases/_list.html.erb, app/views/showcases/edit.html.erb, app/views/showcases/show.json.jbuilder, app/views/showcases/title.html.erb, config/style_guides/.ruby-style.yml, spec/controllers/pages_controller_spec.rb, spec/controllers/sections_controller_spec.rb, spec/controllers/showcases_controller_spec.rb, spec/services/destroy/showcase_spec.rb
The @id field in now links to the api pages instead of to the honeycomb UI. 
I've changed all pages and showcases to use the unique_id field for their uri instead so that we can easily parse the v1 url to link to these resources.
This is already getting very messy and I'm worried about the complexity and readability as we move forward. There's already discussion about how things should have been done - separating the API from the UI - but I think it's worth talking about seriously so this codebase can be more maintainable.
=> Item deletion had bad links for associated pages/showcases

app/assets/stylesheets/ui-customizations.css.scss, app/views/layouts/application.html.erb
The icons on the right and left of the metadata fields on the form seem to be missing in IE 11.
=> DEC-977 Icons not showing up on metadata form in IE 11

app/assets/javascripts/components/showcase_editor/ShowcaseEditorTitle.jsx
If honeypot didn't have a thumbnail/small image for a showcase, the showcase edit button wouldn't show up. 
This is part of a larger issue where we just blindly index into dictionaries without checking if they keys exist. I'm not sure the best way to correct this in javascript (other than add if statements). In python there's dict.get(key, default) which allows for safe indexing all the time since default can be an empty dictionary. eg. we would do image.get("thumbnail/small", {}).get("contenturl", ""). I haven't found an equivalent in javascript as of yet.
=> DEC-929 showcase thumbnails

app/form/section_form.rb, spec/form/section_form_spec.rb
The section#new action was still assuming internal id instead of public id for showcases. I've changed the query to use public_find instead.
=> DEC-1284 Adding text section would hit error

app/assets/stylesheets/ui-customizations.css.scss, app/views/layouts/application.html.erb
* Preproduction banner was checking specifically for “pprd”, I’m
guessing it’s actually preproduction on the server or something.
* Changed to show banner whenever environment is not “production”, so
it will show up on development too now.
=> Fix environment banner

Gemfile, Gemfile.lock
Basically the gem react_rails_img does not recognize the fact we have a pre_production env.  So far I have forked the gem.  
https://github.com/jonhartzler/react-rails-img
I will probably make a pull request with the project.
=> update gem to point to one that works in our environment.

app/assets/javascripts/components.js, app/assets/javascripts/components/CsvImportButton.jsx, app/assets/javascripts/components/GoogleExportButton.jsx, app/assets/javascripts/components/GoogleImportButton.jsx, app/assets/javascripts/components/ImportResultsDialog.jsx, app/assets/javascripts/components/search/SearchPage.jsx, app/assets/javascripts/mixins/GooglePickerMixin.jsx, app/assets/stylesheets/ui-customizations.css.scss, app/controllers/import_controller.rb, app/controllers/v1/import_controller.rb, app/models/waggle/adapters/solr/session.rb, app/services/create_items.rb, app/services/csv_create_items.rb, app/services/find_or_create_item.rb, app/services/google_create_items.rb, app/services/index/collection.rb, app/services/save_item.rb, app/views/items/_action_bar.html.erb, config/routes.rb, lib/tasks/search.rake, spec/controllers/v1/import_controller_spec.rb, spec/models/waggle/adapters/solr/session_spec.rb, spec/services/create_items_spec.rb, spec/services/csv_create_items_spec.rb, spec/services/find_or_create_item_spec.rb, spec/services/google_create_items_spec.rb, spec/services/index/collection_spec.rb, spec/services/save_item_spec.rb
- Adds support for importing metadata directly from a CSV file. The file must be UTF-8.
- Changes indexing to batch items per collection. This amounts to a 9x speedup on importing large collections. This impacts this new csv import, the existing google import, and the rake task for reindexing all collections.
=> Import CSV

app/assets/javascripts/components.js, app/assets/javascripts/components/DeleteButton.jsx, app/assets/javascripts/components/EntriesList.jsx, app/assets/javascripts/components/search/SearchPage.jsx, app/assets/javascripts/mixins/DialogMixin.jsx, app/controllers/v1/pages_controller.rb, app/controllers/v1/showcases_controller.rb, app/views/pages/index.html.erb, app/views/showcases/index.html.erb, config/routes.rb, spec/controllers/v1/pages_controller_spec.rb, spec/controllers/v1/showcases_controller_spec.rb
The request was for a quick way to delete items.
Initial implementation was with checkboxes in the item listing view which would then mass-delete all selected items. Unfortunately, getting information for each item on weather or not it can be deleted was expensive and slow.
Instead, I went with a delete button on the list view for each item which will save a few page transitions at least. I added these buttons to the items/pages/and showcases listings.
=> DEC-450 Quick delete button(s)

app/models/waggle/adapters/solr/index/item.rb, spec/models/waggle/adapters/solr/index/item_spec.rb, spec/models/waggle/adapters/solr/session_spec.rb
The problem was duplication of items in the index, which caused react to flatten items in the array due to duplicate keys. We were using a combination of item.unique_id and item.type to uniquely identify the object to solr. We now have items with different types (ex: MetadataOnlyObject, VideoObject, etc), so this no longer works. Additionally, item.unique_id is only guaranteed to be unique within a collection. Changed this to use the collection.unique_id + item.unique_id when identifying the object in solr. This will mean we need to reindex after a deploy.
=> Bugfix: Video thumbnail not showing correctly on Beehive pprd

app/decorators/item_decorator.rb, app/policy/can_delete.rb, app/queries/item_query.rb, app/queries/page_query.rb, app/queries/showcase_query.rb, app/services/destroy/collection.rb, app/services/destroy/item.rb, app/services/destroy/page.rb, app/services/destroy/showcase.rb, spec/controllers/pages_controller_spec.rb, spec/controllers/showcases_controller_spec.rb, spec/controllers/v1/pages_controller_spec.rb, spec/controllers/v1/showcases_controller_spec.rb, spec/services/destroy/collection_spec.rb, spec/services/destroy/item_spec.rb, spec/services/destroy/page_spec.rb, spec/services/destroy/showcase_spec.rb
The showcase and page quick delete buttons didn't check if the item could be deleted, which would break the site path. This no longer happens.
=> Fix showcase and page quick delete buttons

app/decorators/v1/showcase_json_decorator.rb, app/models/showcase.rb, app/values/cache_keys/custom/v1_showcases.rb, spec/controllers/v1/showcases_controller_spec.rb, spec/values/cache_keys/custom/v1_showcases_spec.rb
-Changed cache key for v1 showcase to also include all associated media
-Added an association to showcases to make it easier to get the collection of media associated with a collection (through sections then items)
=> Bugfix: Video thumbnail cache

app/assets/javascripts/components/showcase_editor/SectionImage.jsx
Section images were still using an old field that doesn't update when the underlying item is updated. There will be another task to remove this old field (section.image) completely from the model.
=> DEC-1315 Section thumbnails

app/services/replace_page_item.rb, spec/services/replace_page_item_spec.rb, spec/services/save_media_thumbnail_spec.rb
Problem was when importing metadata for a video item that was included in a page. Changed ReplacePageItem to deal with non image type objects.
=> Bugfix Import CSV

app/services/google_export_items.rb, app/services/rewrite_item_metadata_for_export.rb, spec/services/google_export_items_spec.rb, spec/services/rewrite_item_metadata_for_export_spec.rb
Changed export to add the parent's user_defined_id when the item has a parent.
=> Export parents

Gemfile, Gemfile.lock, app/models/waggle/adapters/solr/index/item.rb, app/models/waggle/adapters/solr/search/hit.rb, app/models/waggle/adapters/solr/session.rb, app/models/waggle/item.rb, app/models/waggle/search/hit.rb, app/views/v1/search/_hit.json.jbuilder, spec/fixtures/v1/items/pig-in-mud.json, spec/models/waggle/adapters/solr/index/item_spec.rb, spec/models/waggle/adapters/solr/session_spec.rb, spec/models/waggle/item_spec.rb
Altered indexing to correctly account for children. 
This required updating the rsolr gem from 1.0 to 2.0, which had a bug with only having one child, which I fixed in a fork of the repo.
I'm open to suggestions on what we want the identifier to be for parents. Right now it's just a string relation is_parent: "true" or "false"
=> DEC-1340 Indexing

app/services/create_items.rb, app/services/csv_create_items.rb, app/services/google_create_items.rb, app/services/google_session.rb, app/services/rewrite_item_metadata.rb, spec/services/create_items_spec.rb, spec/services/csv_create_items_spec.rb, spec/services/google_create_items_spec.rb, spec/services/google_session_spec.rb, spec/services/rewrite_item_metadata_fields_spec.rb
This changes the google and csv import routines so that they can handle parent/child associations identified by a "Parent Identifier" column.
Summary of changes:
- Changed the metadata rewrite to lookup the parent by the user defined id anytime a parent is given. If the parent exists, it adds the associated parent id to the child to create the association.
- Changed any methods that call CreateItems to give parents first, then children, to make sure that new parents are created before the lookup for the child is executed.
- Since the order that the cells are read is no longer preserved when passing the data on to the lower level CreateItems service, and this service is what adds any errors encountered (including the row where it encountered it), I had to start passing the original index …
=> Import parent/child associations

app/models/waggle/adapters/solr/index/item.rb, app/models/waggle/adapters/solr/session.rb, spec/models/waggle/adapters/solr/session_spec.rb
Indexing child relationships causes issues with the solr index in cases where the parent items exist before the relation is created.
I've removed this functionality as we will never be able to use the relation data (in the solr way) anyway.
=> DEC-1340 undo

app/controllers/v1/search_controller.rb, app/models/waggle/adapters/solr/search/result.rb, app/models/waggle/search/query.rb, app/models/waggle/search/result.rb, app/views/items/index.html.erb, app/views/showcases/edit.html.erb, app/views/v1/search/_group.json.jbuilder, app/views/v1/search/children.json.jbuilder, config/routes.rb, config/style_guides/.ruby-style.yml, spec/controllers/v1/search_controller_spec.rb, spec/fixtures/waggle/solr_grouped_response.json, spec/models/waggle/adapters/solr/search/result_spec.rb, spec/models/waggle/search/query_spec.rb, spec/models/waggle/search/result_spec.rb
Add the `../search/children` route to search only the children items of a collection.
By default, the resulting hits are returned grouped by the parent id. This can be turned off to return flat hits by adding the parameter `no_group=true` to the url.
=> Dec 1254 child search

app/models/item.rb, spec/models/item_spec.rb
We needed to validate that the depth of our relation tree is only 1.
In my timings this added ~20 seconds to the import of the Catholic Social Teachings collection of ~7000 items.
=> DEC-1261 Relation Depth Validation

Gemfile, Gemfile.lock
Having problems with the updated gem. Testing the build without it sisnce we no longer need the parent/child relationship fixes in the gem.
=> Solr gem build fix

lib/tasks/db.rake
Created a rake task to clear out a collection. Eventually it might make sense to have this as an actual service that can be reached from some admin function on a collection, but I didn't want to touch app code for this since we're limited on time.
=> Clear collection

app/policy/user_is_admin.rb, spec/policy/user_is_admin_spec.rb
This exception shows up in our Errbit logs. By adding a guard clause,
we will stop throwing exceptions.
=> Addressing `NoMethodError: undefined method `admin?' for nil:NilClass`

lib/tasks/adhoc_upload_images.rake
Something weird happens with openuri#open nowadays when it parses the filename that seems to kill the honeypot job. Changed to URI.parse and it preserves the original file name, which seems to work better.
Changed to use Metadata::Setter for setting the item name based on file name. (see https://github.com/ndlib/honeycomb/pull/326)
=> Few fixes for the adhoc import task

app/models/waggle/adapters/solr/search/result.rb
Limit will be applied by UI only.
=> Disregard facet amount limit when fetching facet values for search.

app/assets/javascripts/components/forms/MetaDataConfigurationForm/MetaDataConfigurationForm.jsx, app/controllers/collections_controller.rb, app/decorators/reindex_panel.rb, app/jobs/reindex_collection_job.rb, app/views/collections/_metadata_settings_form.html.erb, app/views/shared/_reindex_panel.html.erb, app/workers/honeycomb_index_worker.rb, config/locales/en.yml, config/routes.rb, lib/tasks/sneakers.rake, spec/controllers/collections_controller_spec.rb, spec/decorators/reindex_panel_spec.rb, spec/jobs/reindex_collection_job_spec.rb, spec/workers/honeycomb_index_worker_spec.rb
This will allow curators to reindex their collections on demand, as is needed when adding facets.
=> DEC-1447 Add reindex button to metadata settings page.

config/deploy/prep.rb, config/environments/prep.rb, config/newrelic.yml, config/secrets.example.yml, config/settings.yml, config/solr.yml, config/sunspot.yml
We need a new environment to point to a different domain without taking down honeycombpprd-vm for the time being. My hope is that once we are done testing, the new "prep" server can act as the testing environment going forward and we can decomission pre_production.
=> Add "prep" environment.

docker-compose.yml, docker/database.yml, docker/rails_entry.sh, spec/newman/smoke.json
This primarily adds tests that are a bit more basic than the others for
running smoke tests. Additionally includes some refactoring of env keys
to be more consistent with other services in the stack.
=> Add basic smoke tests

docker-compose.prod.yml, docker/nginx.conf, docker/nginx_entry.sh
This adds the ability to control how many requests per minute will be
forwarded to the upstream rails service. This is to prevent requests
from overwhelming the rails service and/or the underlying data services
such as solr/db.
=> Add rate limiting

Gemfile, Gemfile.lock, config/initializers/health_bit.rb, config/routes.rb, docker/Dockerfile.rails, docker/rails_entry.sh, docker/rails_migrate.sh
Adds a healthcheck route that explicitly checks for migrations. We will
use this for ECS healthchecks to prevent a new task from serving requests
until migrations are run. This will allow us to get a bit closer to the
way capistrano handles the deploy, ie deploy the new version, run migrate,
then make the new deployment live. This will help us reduce the amount
of time between running migrations and cutting over to the new release.
=> Add healthchecks

.dockerignore, docker-compose.prod.yml, docker/Dockerfile.rails, docker/rails_entry.sh
This fixes an issue with uploading images when deployed to ECS. Rails
expects public/system to exist, but is not kept in git, so image uploads
were failing to get moved by paperclip to the correct dir. Changed the
link of /project_root/public/system/images/honeycomb -> /mnt/honeycomb
to instead be a link of /project_root/public/system -> /mnt/system. The
issue was likely obfuscated locally because I had files in public/system
from a local execution of rails, so the docker build was copying these
in. Changed the dockerignore to ignore this directory so that the
behavior more closely match what the docker context will look like in a
fresh checkout.
Additionally moved away from running rails as root and added a rails user
(uid 999) that will run the processes in the container.
=> Fix public images

Gemfile.lock, docker-compose.yml, docker/Dockerfile.rails, docker/hesburgh_api.yml
The previous deploy strategy expected a config/hesburgh_api.yml to exist
on the host. This file configures how to connect to the Hesburgh API for
searching for users. This PR is to add this file to the Docker build
and instructs rails to read the url and token values from env. This should
fix an issue with searching for users when adding admins to the site, or
when adding editors to a collection.
=> Fix editors in Docker env
